// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: stream/v1/api.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct Stream_V1_HealthResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var status: String = String()

  public var uptime: String = String()

  public var channels: Int32 {
    get {_channels ?? 0}
    set {_channels = newValue}
  }
  /// Returns true if `channels` has been explicitly set.
  public var hasChannels: Bool {self._channels != nil}
  /// Clears the value of `channels`. Subsequent reads from it will return its default value.
  public mutating func clearChannels() {self._channels = nil}

  public var healthy: Int32 {
    get {_healthy ?? 0}
    set {_healthy = newValue}
  }
  /// Returns true if `healthy` has been explicitly set.
  public var hasHealthy: Bool {self._healthy != nil}
  /// Clears the value of `healthy`. Subsequent reads from it will return its default value.
  public mutating func clearHealthy() {self._healthy = nil}

  public var lastProbe: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_lastProbe ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_lastProbe = newValue}
  }
  /// Returns true if `lastProbe` has been explicitly set.
  public var hasLastProbe: Bool {self._lastProbe != nil}
  /// Clears the value of `lastProbe`. Subsequent reads from it will return its default value.
  public mutating func clearLastProbe() {self._lastProbe = nil}

  public var version: String = String()

  public var serverName: String {
    get {_serverName ?? String()}
    set {_serverName = newValue}
  }
  /// Returns true if `serverName` has been explicitly set.
  public var hasServerName: Bool {self._serverName != nil}
  /// Clears the value of `serverName`. Subsequent reads from it will return its default value.
  public mutating func clearServerName() {self._serverName = nil}

  public var addr: String {
    get {_addr ?? String()}
    set {_addr = newValue}
  }
  /// Returns true if `addr` has been explicitly set.
  public var hasAddr: Bool {self._addr != nil}
  /// Clears the value of `addr`. Subsequent reads from it will return its default value.
  public mutating func clearAddr() {self._addr = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _channels: Int32? = nil
  fileprivate var _healthy: Int32? = nil
  fileprivate var _lastProbe: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  fileprivate var _serverName: String? = nil
  fileprivate var _addr: String? = nil
}

public nonisolated struct Stream_V1_ChannelResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  public var name: String = String()

  public var groupTitle: String = String()

  public var tvgID: String = String()

  public var logoURL: String = String()

  public var healthy: Bool = false

  public var activeScore: Double = 0

  public var candidateCount: Int32 = 0

  public var hasActiveLink_p: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Stream_V1_ChannelListResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var channels: [Stream_V1_ChannelResponse] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Stream_V1_ChannelDetailResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  public var name: String = String()

  public var groupTitle: String = String()

  public var tvgID: String = String()

  public var logoURL: String = String()

  public var keywords: [String] = []

  public var activeLink: Stream_V1_LinkScoreResponse {
    get {_activeLink ?? Stream_V1_LinkScoreResponse()}
    set {_activeLink = newValue}
  }
  /// Returns true if `activeLink` has been explicitly set.
  public var hasActiveLink: Bool {self._activeLink != nil}
  /// Clears the value of `activeLink`. Subsequent reads from it will return its default value.
  public mutating func clearActiveLink() {self._activeLink = nil}

  public var candidates: [Stream_V1_LinkScoreResponse] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _activeLink: Stream_V1_LinkScoreResponse? = nil
}

public nonisolated struct Stream_V1_LinkScoreResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var url: String = String()

  public var score: Double = 0

  public var latencyMs: Int32 = 0

  public var state: String = String()

  public var failCount: Int32 = 0

  public var headers: Dictionary<String,String> = [:]

  public var failureReason: String {
    get {_failureReason ?? String()}
    set {_failureReason = newValue}
  }
  /// Returns true if `failureReason` has been explicitly set.
  public var hasFailureReason: Bool {self._failureReason != nil}
  /// Clears the value of `failureReason`. Subsequent reads from it will return its default value.
  public mutating func clearFailureReason() {self._failureReason = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _failureReason: String? = nil
}

/// NOTE: stream_headers added here to match UpdateChannelRequest.
/// Fixes a real drift found during T1.2 drafting: Create previously had
/// no way to set headers even though Update did on all three platforms.
public nonisolated struct Stream_V1_CreateChannelRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String = String()

  public var groupTitle: String = String()

  public var tvgID: String = String()

  public var logoURL: String = String()

  public var streamURL: String = String()

  public var keywords: [String] = []

  public var streamHeaders: Dictionary<String,String> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Stream_V1_UpdateChannelRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String {
    get {_name ?? String()}
    set {_name = newValue}
  }
  /// Returns true if `name` has been explicitly set.
  public var hasName: Bool {self._name != nil}
  /// Clears the value of `name`. Subsequent reads from it will return its default value.
  public mutating func clearName() {self._name = nil}

  public var groupTitle: String {
    get {_groupTitle ?? String()}
    set {_groupTitle = newValue}
  }
  /// Returns true if `groupTitle` has been explicitly set.
  public var hasGroupTitle: Bool {self._groupTitle != nil}
  /// Clears the value of `groupTitle`. Subsequent reads from it will return its default value.
  public mutating func clearGroupTitle() {self._groupTitle = nil}

  public var streamURL: String {
    get {_streamURL ?? String()}
    set {_streamURL = newValue}
  }
  /// Returns true if `streamURL` has been explicitly set.
  public var hasStreamURL: Bool {self._streamURL != nil}
  /// Clears the value of `streamURL`. Subsequent reads from it will return its default value.
  public mutating func clearStreamURL() {self._streamURL = nil}

  public var keywords: [String] = []

  public var streamHeaders: Dictionary<String,String> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _name: String? = nil
  fileprivate var _groupTitle: String? = nil
  fileprivate var _streamURL: String? = nil
}

public nonisolated struct Stream_V1_StatusResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var status: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "stream.v1"

nonisolated extension Stream_V1_HealthResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HealthResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}status\0\u{1}uptime\0\u{1}channels\0\u{1}healthy\0\u{3}last_probe\0\u{1}version\0\u{3}server_name\0\u{1}addr\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.status) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.uptime) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self._channels) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self._healthy) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._lastProbe) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.version) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self._serverName) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self._addr) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.status.isEmpty {
      try visitor.visitSingularStringField(value: self.status, fieldNumber: 1)
    }
    if !self.uptime.isEmpty {
      try visitor.visitSingularStringField(value: self.uptime, fieldNumber: 2)
    }
    try { if let v = self._channels {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._healthy {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._lastProbe {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    if !self.version.isEmpty {
      try visitor.visitSingularStringField(value: self.version, fieldNumber: 6)
    }
    try { if let v = self._serverName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._addr {
      try visitor.visitSingularStringField(value: v, fieldNumber: 8)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Stream_V1_HealthResponse, rhs: Stream_V1_HealthResponse) -> Bool {
    if lhs.status != rhs.status {return false}
    if lhs.uptime != rhs.uptime {return false}
    if lhs._channels != rhs._channels {return false}
    if lhs._healthy != rhs._healthy {return false}
    if lhs._lastProbe != rhs._lastProbe {return false}
    if lhs.version != rhs.version {return false}
    if lhs._serverName != rhs._serverName {return false}
    if lhs._addr != rhs._addr {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Stream_V1_ChannelResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ChannelResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}name\0\u{3}group_title\0\u{3}tvg_id\0\u{3}logo_url\0\u{1}healthy\0\u{3}active_score\0\u{3}candidate_count\0\u{3}has_active_link\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.groupTitle) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.tvgID) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.logoURL) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.healthy) }()
      case 7: try { try decoder.decodeSingularDoubleField(value: &self.activeScore) }()
      case 8: try { try decoder.decodeSingularInt32Field(value: &self.candidateCount) }()
      case 9: try { try decoder.decodeSingularBoolField(value: &self.hasActiveLink_p) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if !self.groupTitle.isEmpty {
      try visitor.visitSingularStringField(value: self.groupTitle, fieldNumber: 3)
    }
    if !self.tvgID.isEmpty {
      try visitor.visitSingularStringField(value: self.tvgID, fieldNumber: 4)
    }
    if !self.logoURL.isEmpty {
      try visitor.visitSingularStringField(value: self.logoURL, fieldNumber: 5)
    }
    if self.healthy != false {
      try visitor.visitSingularBoolField(value: self.healthy, fieldNumber: 6)
    }
    if self.activeScore.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.activeScore, fieldNumber: 7)
    }
    if self.candidateCount != 0 {
      try visitor.visitSingularInt32Field(value: self.candidateCount, fieldNumber: 8)
    }
    if self.hasActiveLink_p != false {
      try visitor.visitSingularBoolField(value: self.hasActiveLink_p, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Stream_V1_ChannelResponse, rhs: Stream_V1_ChannelResponse) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.name != rhs.name {return false}
    if lhs.groupTitle != rhs.groupTitle {return false}
    if lhs.tvgID != rhs.tvgID {return false}
    if lhs.logoURL != rhs.logoURL {return false}
    if lhs.healthy != rhs.healthy {return false}
    if lhs.activeScore != rhs.activeScore {return false}
    if lhs.candidateCount != rhs.candidateCount {return false}
    if lhs.hasActiveLink_p != rhs.hasActiveLink_p {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Stream_V1_ChannelListResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ChannelListResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}channels\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.channels) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.channels.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.channels, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Stream_V1_ChannelListResponse, rhs: Stream_V1_ChannelListResponse) -> Bool {
    if lhs.channels != rhs.channels {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Stream_V1_ChannelDetailResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ChannelDetailResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}name\0\u{3}group_title\0\u{3}tvg_id\0\u{3}logo_url\0\u{1}keywords\0\u{3}active_link\0\u{1}candidates\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.groupTitle) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.tvgID) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.logoURL) }()
      case 6: try { try decoder.decodeRepeatedStringField(value: &self.keywords) }()
      case 7: try { try decoder.decodeSingularMessageField(value: &self._activeLink) }()
      case 8: try { try decoder.decodeRepeatedMessageField(value: &self.candidates) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if !self.groupTitle.isEmpty {
      try visitor.visitSingularStringField(value: self.groupTitle, fieldNumber: 3)
    }
    if !self.tvgID.isEmpty {
      try visitor.visitSingularStringField(value: self.tvgID, fieldNumber: 4)
    }
    if !self.logoURL.isEmpty {
      try visitor.visitSingularStringField(value: self.logoURL, fieldNumber: 5)
    }
    if !self.keywords.isEmpty {
      try visitor.visitRepeatedStringField(value: self.keywords, fieldNumber: 6)
    }
    try { if let v = self._activeLink {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    } }()
    if !self.candidates.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.candidates, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Stream_V1_ChannelDetailResponse, rhs: Stream_V1_ChannelDetailResponse) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.name != rhs.name {return false}
    if lhs.groupTitle != rhs.groupTitle {return false}
    if lhs.tvgID != rhs.tvgID {return false}
    if lhs.logoURL != rhs.logoURL {return false}
    if lhs.keywords != rhs.keywords {return false}
    if lhs._activeLink != rhs._activeLink {return false}
    if lhs.candidates != rhs.candidates {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Stream_V1_LinkScoreResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LinkScoreResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}url\0\u{1}score\0\u{3}latency_ms\0\u{1}state\0\u{3}fail_count\0\u{1}headers\0\u{3}failure_reason\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.url) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.score) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.latencyMs) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.state) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.failCount) }()
      case 6: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.headers) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self._failureReason) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.url.isEmpty {
      try visitor.visitSingularStringField(value: self.url, fieldNumber: 1)
    }
    if self.score.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.score, fieldNumber: 2)
    }
    if self.latencyMs != 0 {
      try visitor.visitSingularInt32Field(value: self.latencyMs, fieldNumber: 3)
    }
    if !self.state.isEmpty {
      try visitor.visitSingularStringField(value: self.state, fieldNumber: 4)
    }
    if self.failCount != 0 {
      try visitor.visitSingularInt32Field(value: self.failCount, fieldNumber: 5)
    }
    if !self.headers.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.headers, fieldNumber: 6)
    }
    try { if let v = self._failureReason {
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Stream_V1_LinkScoreResponse, rhs: Stream_V1_LinkScoreResponse) -> Bool {
    if lhs.url != rhs.url {return false}
    if lhs.score != rhs.score {return false}
    if lhs.latencyMs != rhs.latencyMs {return false}
    if lhs.state != rhs.state {return false}
    if lhs.failCount != rhs.failCount {return false}
    if lhs.headers != rhs.headers {return false}
    if lhs._failureReason != rhs._failureReason {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Stream_V1_CreateChannelRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CreateChannelRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{3}group_title\0\u{3}tvg_id\0\u{3}logo_url\0\u{3}stream_url\0\u{1}keywords\0\u{3}stream_headers\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.groupTitle) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.tvgID) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.logoURL) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.streamURL) }()
      case 6: try { try decoder.decodeRepeatedStringField(value: &self.keywords) }()
      case 7: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.streamHeaders) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.groupTitle.isEmpty {
      try visitor.visitSingularStringField(value: self.groupTitle, fieldNumber: 2)
    }
    if !self.tvgID.isEmpty {
      try visitor.visitSingularStringField(value: self.tvgID, fieldNumber: 3)
    }
    if !self.logoURL.isEmpty {
      try visitor.visitSingularStringField(value: self.logoURL, fieldNumber: 4)
    }
    if !self.streamURL.isEmpty {
      try visitor.visitSingularStringField(value: self.streamURL, fieldNumber: 5)
    }
    if !self.keywords.isEmpty {
      try visitor.visitRepeatedStringField(value: self.keywords, fieldNumber: 6)
    }
    if !self.streamHeaders.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.streamHeaders, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Stream_V1_CreateChannelRequest, rhs: Stream_V1_CreateChannelRequest) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.groupTitle != rhs.groupTitle {return false}
    if lhs.tvgID != rhs.tvgID {return false}
    if lhs.logoURL != rhs.logoURL {return false}
    if lhs.streamURL != rhs.streamURL {return false}
    if lhs.keywords != rhs.keywords {return false}
    if lhs.streamHeaders != rhs.streamHeaders {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Stream_V1_UpdateChannelRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".UpdateChannelRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{3}group_title\0\u{3}stream_url\0\u{1}keywords\0\u{3}stream_headers\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._groupTitle) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._streamURL) }()
      case 4: try { try decoder.decodeRepeatedStringField(value: &self.keywords) }()
      case 5: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.streamHeaders) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._name {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._groupTitle {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._streamURL {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    if !self.keywords.isEmpty {
      try visitor.visitRepeatedStringField(value: self.keywords, fieldNumber: 4)
    }
    if !self.streamHeaders.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.streamHeaders, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Stream_V1_UpdateChannelRequest, rhs: Stream_V1_UpdateChannelRequest) -> Bool {
    if lhs._name != rhs._name {return false}
    if lhs._groupTitle != rhs._groupTitle {return false}
    if lhs._streamURL != rhs._streamURL {return false}
    if lhs.keywords != rhs.keywords {return false}
    if lhs.streamHeaders != rhs.streamHeaders {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Stream_V1_StatusResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StatusResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}status\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.status) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.status.isEmpty {
      try visitor.visitSingularStringField(value: self.status, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Stream_V1_StatusResponse, rhs: Stream_V1_StatusResponse) -> Bool {
    if lhs.status != rhs.status {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
