// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/api.proto
// Protobuf Java Version: 4.29.0

package com.stream.v1;

public interface ChannelListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.v1.ChannelListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .stream.v1.ChannelResponse channels = 1 [json_name = "channels"];</code>
   */
  java.util.List<com.stream.v1.ChannelResponse> 
      getChannelsList();
  /**
   * <code>repeated .stream.v1.ChannelResponse channels = 1 [json_name = "channels"];</code>
   */
  com.stream.v1.ChannelResponse getChannels(int index);
  /**
   * <code>repeated .stream.v1.ChannelResponse channels = 1 [json_name = "channels"];</code>
   */
  int getChannelsCount();
  /**
   * <code>repeated .stream.v1.ChannelResponse channels = 1 [json_name = "channels"];</code>
   */
  java.util.List<? extends com.stream.v1.ChannelResponseOrBuilder> 
      getChannelsOrBuilderList();
  /**
   * <code>repeated .stream.v1.ChannelResponse channels = 1 [json_name = "channels"];</code>
   */
  com.stream.v1.ChannelResponseOrBuilder getChannelsOrBuilder(
      int index);
}
