// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/api.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.stream.v1;

@kotlin.jvm.JvmName("-initializecreateChannelRequest")
public inline fun createChannelRequest(block: com.stream.v1.CreateChannelRequestKt.Dsl.() -> kotlin.Unit): com.stream.v1.CreateChannelRequest =
  com.stream.v1.CreateChannelRequestKt.Dsl._create(com.stream.v1.CreateChannelRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * NOTE: stream_headers added here to match UpdateChannelRequest.
 * Fixes a real drift found during T1.2 drafting: Create previously had
 * no way to set headers even though Update did on all three platforms.
 * ```
 *
 * Protobuf type `stream.v1.CreateChannelRequest`
 */
public object CreateChannelRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.stream.v1.CreateChannelRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.stream.v1.CreateChannelRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.stream.v1.CreateChannelRequest = _builder.build()

    /**
     * `string name = 1 [json_name = "name"];`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.name
      @JvmName("setName")
      set(value) {
        _builder.name = value
      }
    /**
     * `string name = 1 [json_name = "name"];`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `string group_title = 2 [json_name = "groupTitle"];`
     */
    public var groupTitle: kotlin.String
      @JvmName("getGroupTitle")
      get() = _builder.groupTitle
      @JvmName("setGroupTitle")
      set(value) {
        _builder.groupTitle = value
      }
    /**
     * `string group_title = 2 [json_name = "groupTitle"];`
     */
    public fun clearGroupTitle() {
      _builder.clearGroupTitle()
    }

    /**
     * `string tvg_id = 3 [json_name = "tvgId"];`
     */
    public var tvgId: kotlin.String
      @JvmName("getTvgId")
      get() = _builder.tvgId
      @JvmName("setTvgId")
      set(value) {
        _builder.tvgId = value
      }
    /**
     * `string tvg_id = 3 [json_name = "tvgId"];`
     */
    public fun clearTvgId() {
      _builder.clearTvgId()
    }

    /**
     * `string logo_url = 4 [json_name = "logoUrl"];`
     */
    public var logoUrl: kotlin.String
      @JvmName("getLogoUrl")
      get() = _builder.logoUrl
      @JvmName("setLogoUrl")
      set(value) {
        _builder.logoUrl = value
      }
    /**
     * `string logo_url = 4 [json_name = "logoUrl"];`
     */
    public fun clearLogoUrl() {
      _builder.clearLogoUrl()
    }

    /**
     * `string stream_url = 5 [json_name = "streamUrl"];`
     */
    public var streamUrl: kotlin.String
      @JvmName("getStreamUrl")
      get() = _builder.streamUrl
      @JvmName("setStreamUrl")
      set(value) {
        _builder.streamUrl = value
      }
    /**
     * `string stream_url = 5 [json_name = "streamUrl"];`
     */
    public fun clearStreamUrl() {
      _builder.clearStreamUrl()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class KeywordsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string keywords = 6 [json_name = "keywords"];`
     * @return A list containing the keywords.
     */
    public val keywords: com.google.protobuf.kotlin.DslList<kotlin.String, KeywordsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.keywordsList
      )
    /**
     * `repeated string keywords = 6 [json_name = "keywords"];`
     * @param value The keywords to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addKeywords")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, KeywordsProxy>.add(value: kotlin.String) {
      _builder.addKeywords(value)
    }
    /**
     * `repeated string keywords = 6 [json_name = "keywords"];`
     * @param value The keywords to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignKeywords")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, KeywordsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string keywords = 6 [json_name = "keywords"];`
     * @param values The keywords to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllKeywords")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, KeywordsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllKeywords(values)
    }
    /**
     * `repeated string keywords = 6 [json_name = "keywords"];`
     * @param values The keywords to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllKeywords")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, KeywordsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string keywords = 6 [json_name = "keywords"];`
     * @param index The index to set the value at.
     * @param value The keywords to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setKeywords")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, KeywordsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setKeywords(index, value)
    }/**
     * `repeated string keywords = 6 [json_name = "keywords"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearKeywords")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, KeywordsProxy>.clear() {
      _builder.clearKeywords()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class StreamHeadersProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `map<string, string> stream_headers = 7 [json_name = "streamHeaders"];`
     */
     public val streamHeaders: com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, StreamHeadersProxy>
      @kotlin.jvm.JvmSynthetic
      @JvmName("getStreamHeadersMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.streamHeadersMap
      )
    /**
     * `map<string, string> stream_headers = 7 [json_name = "streamHeaders"];`
     */
    @JvmName("putStreamHeaders")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, StreamHeadersProxy>
      .put(key: kotlin.String, value: kotlin.String) {
         _builder.putStreamHeaders(key, value)
       }
    /**
     * `map<string, string> stream_headers = 7 [json_name = "streamHeaders"];`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("setStreamHeaders")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, StreamHeadersProxy>
      .set(key: kotlin.String, value: kotlin.String) {
         put(key, value)
       }
    /**
     * `map<string, string> stream_headers = 7 [json_name = "streamHeaders"];`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("removeStreamHeaders")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, StreamHeadersProxy>
      .remove(key: kotlin.String) {
         _builder.removeStreamHeaders(key)
       }
    /**
     * `map<string, string> stream_headers = 7 [json_name = "streamHeaders"];`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("putAllStreamHeaders")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, StreamHeadersProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, kotlin.String>) {
         _builder.putAllStreamHeaders(map)
       }
    /**
     * `map<string, string> stream_headers = 7 [json_name = "streamHeaders"];`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("clearStreamHeaders")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, StreamHeadersProxy>
      .clear() {
         _builder.clearStreamHeaders()
       }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.stream.v1.CreateChannelRequest.copy(block: `com.stream.v1`.CreateChannelRequestKt.Dsl.() -> kotlin.Unit): com.stream.v1.CreateChannelRequest =
  `com.stream.v1`.CreateChannelRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

