// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/api.proto
// Protobuf Java Version: 4.29.0

package com.stream.v1;

public interface CreateChannelRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.v1.CreateChannelRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string group_title = 2 [json_name = "groupTitle"];</code>
   * @return The groupTitle.
   */
  java.lang.String getGroupTitle();
  /**
   * <code>string group_title = 2 [json_name = "groupTitle"];</code>
   * @return The bytes for groupTitle.
   */
  com.google.protobuf.ByteString
      getGroupTitleBytes();

  /**
   * <code>string tvg_id = 3 [json_name = "tvgId"];</code>
   * @return The tvgId.
   */
  java.lang.String getTvgId();
  /**
   * <code>string tvg_id = 3 [json_name = "tvgId"];</code>
   * @return The bytes for tvgId.
   */
  com.google.protobuf.ByteString
      getTvgIdBytes();

  /**
   * <code>string logo_url = 4 [json_name = "logoUrl"];</code>
   * @return The logoUrl.
   */
  java.lang.String getLogoUrl();
  /**
   * <code>string logo_url = 4 [json_name = "logoUrl"];</code>
   * @return The bytes for logoUrl.
   */
  com.google.protobuf.ByteString
      getLogoUrlBytes();

  /**
   * <code>string stream_url = 5 [json_name = "streamUrl"];</code>
   * @return The streamUrl.
   */
  java.lang.String getStreamUrl();
  /**
   * <code>string stream_url = 5 [json_name = "streamUrl"];</code>
   * @return The bytes for streamUrl.
   */
  com.google.protobuf.ByteString
      getStreamUrlBytes();

  /**
   * <code>repeated string keywords = 6 [json_name = "keywords"];</code>
   * @return A list containing the keywords.
   */
  java.util.List<java.lang.String>
      getKeywordsList();
  /**
   * <code>repeated string keywords = 6 [json_name = "keywords"];</code>
   * @return The count of keywords.
   */
  int getKeywordsCount();
  /**
   * <code>repeated string keywords = 6 [json_name = "keywords"];</code>
   * @param index The index of the element to return.
   * @return The keywords at the given index.
   */
  java.lang.String getKeywords(int index);
  /**
   * <code>repeated string keywords = 6 [json_name = "keywords"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the keywords at the given index.
   */
  com.google.protobuf.ByteString
      getKeywordsBytes(int index);

  /**
   * <code>map&lt;string, string&gt; stream_headers = 7 [json_name = "streamHeaders"];</code>
   */
  int getStreamHeadersCount();
  /**
   * <code>map&lt;string, string&gt; stream_headers = 7 [json_name = "streamHeaders"];</code>
   */
  boolean containsStreamHeaders(
      java.lang.String key);
  /**
   * Use {@link #getStreamHeadersMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getStreamHeaders();
  /**
   * <code>map&lt;string, string&gt; stream_headers = 7 [json_name = "streamHeaders"];</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getStreamHeadersMap();
  /**
   * <code>map&lt;string, string&gt; stream_headers = 7 [json_name = "streamHeaders"];</code>
   */
  /* nullable */
java.lang.String getStreamHeadersOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; stream_headers = 7 [json_name = "streamHeaders"];</code>
   */
  java.lang.String getStreamHeadersOrThrow(
      java.lang.String key);
}
