// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/api.proto
// Protobuf Java Version: 4.29.0

package com.stream.v1;

/**
 * <pre>
 * NOTE: stream_headers added here to match UpdateChannelRequest.
 * Fixes a real drift found during T1.2 drafting: Create previously had
 * no way to set headers even though Update did on all three platforms.
 * </pre>
 *
 * Protobuf type {@code stream.v1.CreateChannelRequest}
 */
public final class CreateChannelRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:stream.v1.CreateChannelRequest)
    CreateChannelRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      CreateChannelRequest.class.getName());
  }
  // Use CreateChannelRequest.newBuilder() to construct.
  private CreateChannelRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CreateChannelRequest() {
    name_ = "";
    groupTitle_ = "";
    tvgId_ = "";
    logoUrl_ = "";
    streamUrl_ = "";
    keywords_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.stream.v1.ApiProto.internal_static_stream_v1_CreateChannelRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 7:
        return internalGetStreamHeaders();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.stream.v1.ApiProto.internal_static_stream_v1_CreateChannelRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.stream.v1.CreateChannelRequest.class, com.stream.v1.CreateChannelRequest.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GROUP_TITLE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object groupTitle_ = "";
  /**
   * <code>string group_title = 2 [json_name = "groupTitle"];</code>
   * @return The groupTitle.
   */
  @java.lang.Override
  public java.lang.String getGroupTitle() {
    java.lang.Object ref = groupTitle_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      groupTitle_ = s;
      return s;
    }
  }
  /**
   * <code>string group_title = 2 [json_name = "groupTitle"];</code>
   * @return The bytes for groupTitle.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGroupTitleBytes() {
    java.lang.Object ref = groupTitle_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      groupTitle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TVG_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tvgId_ = "";
  /**
   * <code>string tvg_id = 3 [json_name = "tvgId"];</code>
   * @return The tvgId.
   */
  @java.lang.Override
  public java.lang.String getTvgId() {
    java.lang.Object ref = tvgId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tvgId_ = s;
      return s;
    }
  }
  /**
   * <code>string tvg_id = 3 [json_name = "tvgId"];</code>
   * @return The bytes for tvgId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTvgIdBytes() {
    java.lang.Object ref = tvgId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tvgId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOGO_URL_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object logoUrl_ = "";
  /**
   * <code>string logo_url = 4 [json_name = "logoUrl"];</code>
   * @return The logoUrl.
   */
  @java.lang.Override
  public java.lang.String getLogoUrl() {
    java.lang.Object ref = logoUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      logoUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string logo_url = 4 [json_name = "logoUrl"];</code>
   * @return The bytes for logoUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLogoUrlBytes() {
    java.lang.Object ref = logoUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      logoUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STREAM_URL_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object streamUrl_ = "";
  /**
   * <code>string stream_url = 5 [json_name = "streamUrl"];</code>
   * @return The streamUrl.
   */
  @java.lang.Override
  public java.lang.String getStreamUrl() {
    java.lang.Object ref = streamUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      streamUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string stream_url = 5 [json_name = "streamUrl"];</code>
   * @return The bytes for streamUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStreamUrlBytes() {
    java.lang.Object ref = streamUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      streamUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KEYWORDS_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList keywords_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string keywords = 6 [json_name = "keywords"];</code>
   * @return A list containing the keywords.
   */
  public com.google.protobuf.ProtocolStringList
      getKeywordsList() {
    return keywords_;
  }
  /**
   * <code>repeated string keywords = 6 [json_name = "keywords"];</code>
   * @return The count of keywords.
   */
  public int getKeywordsCount() {
    return keywords_.size();
  }
  /**
   * <code>repeated string keywords = 6 [json_name = "keywords"];</code>
   * @param index The index of the element to return.
   * @return The keywords at the given index.
   */
  public java.lang.String getKeywords(int index) {
    return keywords_.get(index);
  }
  /**
   * <code>repeated string keywords = 6 [json_name = "keywords"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the keywords at the given index.
   */
  public com.google.protobuf.ByteString
      getKeywordsBytes(int index) {
    return keywords_.getByteString(index);
  }

  public static final int STREAM_HEADERS_FIELD_NUMBER = 7;
  private static final class StreamHeadersDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.stream.v1.ApiProto.internal_static_stream_v1_CreateChannelRequest_StreamHeadersEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> streamHeaders_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetStreamHeaders() {
    if (streamHeaders_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          StreamHeadersDefaultEntryHolder.defaultEntry);
    }
    return streamHeaders_;
  }
  public int getStreamHeadersCount() {
    return internalGetStreamHeaders().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; stream_headers = 7 [json_name = "streamHeaders"];</code>
   */
  @java.lang.Override
  public boolean containsStreamHeaders(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetStreamHeaders().getMap().containsKey(key);
  }
  /**
   * Use {@link #getStreamHeadersMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getStreamHeaders() {
    return getStreamHeadersMap();
  }
  /**
   * <code>map&lt;string, string&gt; stream_headers = 7 [json_name = "streamHeaders"];</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getStreamHeadersMap() {
    return internalGetStreamHeaders().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; stream_headers = 7 [json_name = "streamHeaders"];</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getStreamHeadersOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetStreamHeaders().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; stream_headers = 7 [json_name = "streamHeaders"];</code>
   */
  @java.lang.Override
  public java.lang.String getStreamHeadersOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetStreamHeaders().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(groupTitle_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, groupTitle_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tvgId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, tvgId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(logoUrl_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, logoUrl_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(streamUrl_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, streamUrl_);
    }
    for (int i = 0; i < keywords_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, keywords_.getRaw(i));
    }
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetStreamHeaders(),
        StreamHeadersDefaultEntryHolder.defaultEntry,
        7);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(groupTitle_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, groupTitle_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tvgId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, tvgId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(logoUrl_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, logoUrl_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(streamUrl_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, streamUrl_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < keywords_.size(); i++) {
        dataSize += computeStringSizeNoTag(keywords_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getKeywordsList().size();
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetStreamHeaders().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      streamHeaders__ = StreamHeadersDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, streamHeaders__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.stream.v1.CreateChannelRequest)) {
      return super.equals(obj);
    }
    com.stream.v1.CreateChannelRequest other = (com.stream.v1.CreateChannelRequest) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getGroupTitle()
        .equals(other.getGroupTitle())) return false;
    if (!getTvgId()
        .equals(other.getTvgId())) return false;
    if (!getLogoUrl()
        .equals(other.getLogoUrl())) return false;
    if (!getStreamUrl()
        .equals(other.getStreamUrl())) return false;
    if (!getKeywordsList()
        .equals(other.getKeywordsList())) return false;
    if (!internalGetStreamHeaders().equals(
        other.internalGetStreamHeaders())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + GROUP_TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getGroupTitle().hashCode();
    hash = (37 * hash) + TVG_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTvgId().hashCode();
    hash = (37 * hash) + LOGO_URL_FIELD_NUMBER;
    hash = (53 * hash) + getLogoUrl().hashCode();
    hash = (37 * hash) + STREAM_URL_FIELD_NUMBER;
    hash = (53 * hash) + getStreamUrl().hashCode();
    if (getKeywordsCount() > 0) {
      hash = (37 * hash) + KEYWORDS_FIELD_NUMBER;
      hash = (53 * hash) + getKeywordsList().hashCode();
    }
    if (!internalGetStreamHeaders().getMap().isEmpty()) {
      hash = (37 * hash) + STREAM_HEADERS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetStreamHeaders().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.stream.v1.CreateChannelRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stream.v1.CreateChannelRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stream.v1.CreateChannelRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stream.v1.CreateChannelRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stream.v1.CreateChannelRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stream.v1.CreateChannelRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stream.v1.CreateChannelRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.stream.v1.CreateChannelRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.stream.v1.CreateChannelRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.stream.v1.CreateChannelRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stream.v1.CreateChannelRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.stream.v1.CreateChannelRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.stream.v1.CreateChannelRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * NOTE: stream_headers added here to match UpdateChannelRequest.
   * Fixes a real drift found during T1.2 drafting: Create previously had
   * no way to set headers even though Update did on all three platforms.
   * </pre>
   *
   * Protobuf type {@code stream.v1.CreateChannelRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:stream.v1.CreateChannelRequest)
      com.stream.v1.CreateChannelRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stream.v1.ApiProto.internal_static_stream_v1_CreateChannelRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 7:
          return internalGetStreamHeaders();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 7:
          return internalGetMutableStreamHeaders();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stream.v1.ApiProto.internal_static_stream_v1_CreateChannelRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stream.v1.CreateChannelRequest.class, com.stream.v1.CreateChannelRequest.Builder.class);
    }

    // Construct using com.stream.v1.CreateChannelRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      groupTitle_ = "";
      tvgId_ = "";
      logoUrl_ = "";
      streamUrl_ = "";
      keywords_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      internalGetMutableStreamHeaders().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.stream.v1.ApiProto.internal_static_stream_v1_CreateChannelRequest_descriptor;
    }

    @java.lang.Override
    public com.stream.v1.CreateChannelRequest getDefaultInstanceForType() {
      return com.stream.v1.CreateChannelRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.stream.v1.CreateChannelRequest build() {
      com.stream.v1.CreateChannelRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.stream.v1.CreateChannelRequest buildPartial() {
      com.stream.v1.CreateChannelRequest result = new com.stream.v1.CreateChannelRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.stream.v1.CreateChannelRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.groupTitle_ = groupTitle_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.tvgId_ = tvgId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.logoUrl_ = logoUrl_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.streamUrl_ = streamUrl_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        keywords_.makeImmutable();
        result.keywords_ = keywords_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.streamHeaders_ = internalGetStreamHeaders();
        result.streamHeaders_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.stream.v1.CreateChannelRequest) {
        return mergeFrom((com.stream.v1.CreateChannelRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.stream.v1.CreateChannelRequest other) {
      if (other == com.stream.v1.CreateChannelRequest.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getGroupTitle().isEmpty()) {
        groupTitle_ = other.groupTitle_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getTvgId().isEmpty()) {
        tvgId_ = other.tvgId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getLogoUrl().isEmpty()) {
        logoUrl_ = other.logoUrl_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getStreamUrl().isEmpty()) {
        streamUrl_ = other.streamUrl_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.keywords_.isEmpty()) {
        if (keywords_.isEmpty()) {
          keywords_ = other.keywords_;
          bitField0_ |= 0x00000020;
        } else {
          ensureKeywordsIsMutable();
          keywords_.addAll(other.keywords_);
        }
        onChanged();
      }
      internalGetMutableStreamHeaders().mergeFrom(
          other.internalGetStreamHeaders());
      bitField0_ |= 0x00000040;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              groupTitle_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              tvgId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              logoUrl_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              streamUrl_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureKeywordsIsMutable();
              keywords_.add(s);
              break;
            } // case 50
            case 58: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              streamHeaders__ = input.readMessage(
                  StreamHeadersDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableStreamHeaders().getMutableMap().put(
                  streamHeaders__.getKey(), streamHeaders__.getValue());
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object groupTitle_ = "";
    /**
     * <code>string group_title = 2 [json_name = "groupTitle"];</code>
     * @return The groupTitle.
     */
    public java.lang.String getGroupTitle() {
      java.lang.Object ref = groupTitle_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groupTitle_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string group_title = 2 [json_name = "groupTitle"];</code>
     * @return The bytes for groupTitle.
     */
    public com.google.protobuf.ByteString
        getGroupTitleBytes() {
      java.lang.Object ref = groupTitle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string group_title = 2 [json_name = "groupTitle"];</code>
     * @param value The groupTitle to set.
     * @return This builder for chaining.
     */
    public Builder setGroupTitle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      groupTitle_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string group_title = 2 [json_name = "groupTitle"];</code>
     * @return This builder for chaining.
     */
    public Builder clearGroupTitle() {
      groupTitle_ = getDefaultInstance().getGroupTitle();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string group_title = 2 [json_name = "groupTitle"];</code>
     * @param value The bytes for groupTitle to set.
     * @return This builder for chaining.
     */
    public Builder setGroupTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      groupTitle_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object tvgId_ = "";
    /**
     * <code>string tvg_id = 3 [json_name = "tvgId"];</code>
     * @return The tvgId.
     */
    public java.lang.String getTvgId() {
      java.lang.Object ref = tvgId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tvgId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tvg_id = 3 [json_name = "tvgId"];</code>
     * @return The bytes for tvgId.
     */
    public com.google.protobuf.ByteString
        getTvgIdBytes() {
      java.lang.Object ref = tvgId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tvgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tvg_id = 3 [json_name = "tvgId"];</code>
     * @param value The tvgId to set.
     * @return This builder for chaining.
     */
    public Builder setTvgId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tvgId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string tvg_id = 3 [json_name = "tvgId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTvgId() {
      tvgId_ = getDefaultInstance().getTvgId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string tvg_id = 3 [json_name = "tvgId"];</code>
     * @param value The bytes for tvgId to set.
     * @return This builder for chaining.
     */
    public Builder setTvgIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tvgId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object logoUrl_ = "";
    /**
     * <code>string logo_url = 4 [json_name = "logoUrl"];</code>
     * @return The logoUrl.
     */
    public java.lang.String getLogoUrl() {
      java.lang.Object ref = logoUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        logoUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string logo_url = 4 [json_name = "logoUrl"];</code>
     * @return The bytes for logoUrl.
     */
    public com.google.protobuf.ByteString
        getLogoUrlBytes() {
      java.lang.Object ref = logoUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        logoUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string logo_url = 4 [json_name = "logoUrl"];</code>
     * @param value The logoUrl to set.
     * @return This builder for chaining.
     */
    public Builder setLogoUrl(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      logoUrl_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string logo_url = 4 [json_name = "logoUrl"];</code>
     * @return This builder for chaining.
     */
    public Builder clearLogoUrl() {
      logoUrl_ = getDefaultInstance().getLogoUrl();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string logo_url = 4 [json_name = "logoUrl"];</code>
     * @param value The bytes for logoUrl to set.
     * @return This builder for chaining.
     */
    public Builder setLogoUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      logoUrl_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object streamUrl_ = "";
    /**
     * <code>string stream_url = 5 [json_name = "streamUrl"];</code>
     * @return The streamUrl.
     */
    public java.lang.String getStreamUrl() {
      java.lang.Object ref = streamUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        streamUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string stream_url = 5 [json_name = "streamUrl"];</code>
     * @return The bytes for streamUrl.
     */
    public com.google.protobuf.ByteString
        getStreamUrlBytes() {
      java.lang.Object ref = streamUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        streamUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string stream_url = 5 [json_name = "streamUrl"];</code>
     * @param value The streamUrl to set.
     * @return This builder for chaining.
     */
    public Builder setStreamUrl(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      streamUrl_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string stream_url = 5 [json_name = "streamUrl"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStreamUrl() {
      streamUrl_ = getDefaultInstance().getStreamUrl();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string stream_url = 5 [json_name = "streamUrl"];</code>
     * @param value The bytes for streamUrl to set.
     * @return This builder for chaining.
     */
    public Builder setStreamUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      streamUrl_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList keywords_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureKeywordsIsMutable() {
      if (!keywords_.isModifiable()) {
        keywords_ = new com.google.protobuf.LazyStringArrayList(keywords_);
      }
      bitField0_ |= 0x00000020;
    }
    /**
     * <code>repeated string keywords = 6 [json_name = "keywords"];</code>
     * @return A list containing the keywords.
     */
    public com.google.protobuf.ProtocolStringList
        getKeywordsList() {
      keywords_.makeImmutable();
      return keywords_;
    }
    /**
     * <code>repeated string keywords = 6 [json_name = "keywords"];</code>
     * @return The count of keywords.
     */
    public int getKeywordsCount() {
      return keywords_.size();
    }
    /**
     * <code>repeated string keywords = 6 [json_name = "keywords"];</code>
     * @param index The index of the element to return.
     * @return The keywords at the given index.
     */
    public java.lang.String getKeywords(int index) {
      return keywords_.get(index);
    }
    /**
     * <code>repeated string keywords = 6 [json_name = "keywords"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the keywords at the given index.
     */
    public com.google.protobuf.ByteString
        getKeywordsBytes(int index) {
      return keywords_.getByteString(index);
    }
    /**
     * <code>repeated string keywords = 6 [json_name = "keywords"];</code>
     * @param index The index to set the value at.
     * @param value The keywords to set.
     * @return This builder for chaining.
     */
    public Builder setKeywords(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureKeywordsIsMutable();
      keywords_.set(index, value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string keywords = 6 [json_name = "keywords"];</code>
     * @param value The keywords to add.
     * @return This builder for chaining.
     */
    public Builder addKeywords(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureKeywordsIsMutable();
      keywords_.add(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string keywords = 6 [json_name = "keywords"];</code>
     * @param values The keywords to add.
     * @return This builder for chaining.
     */
    public Builder addAllKeywords(
        java.lang.Iterable<java.lang.String> values) {
      ensureKeywordsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, keywords_);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string keywords = 6 [json_name = "keywords"];</code>
     * @return This builder for chaining.
     */
    public Builder clearKeywords() {
      keywords_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000020);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string keywords = 6 [json_name = "keywords"];</code>
     * @param value The bytes of the keywords to add.
     * @return This builder for chaining.
     */
    public Builder addKeywordsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureKeywordsIsMutable();
      keywords_.add(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> streamHeaders_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetStreamHeaders() {
      if (streamHeaders_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            StreamHeadersDefaultEntryHolder.defaultEntry);
      }
      return streamHeaders_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableStreamHeaders() {
      if (streamHeaders_ == null) {
        streamHeaders_ = com.google.protobuf.MapField.newMapField(
            StreamHeadersDefaultEntryHolder.defaultEntry);
      }
      if (!streamHeaders_.isMutable()) {
        streamHeaders_ = streamHeaders_.copy();
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return streamHeaders_;
    }
    public int getStreamHeadersCount() {
      return internalGetStreamHeaders().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; stream_headers = 7 [json_name = "streamHeaders"];</code>
     */
    @java.lang.Override
    public boolean containsStreamHeaders(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetStreamHeaders().getMap().containsKey(key);
    }
    /**
     * Use {@link #getStreamHeadersMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getStreamHeaders() {
      return getStreamHeadersMap();
    }
    /**
     * <code>map&lt;string, string&gt; stream_headers = 7 [json_name = "streamHeaders"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getStreamHeadersMap() {
      return internalGetStreamHeaders().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; stream_headers = 7 [json_name = "streamHeaders"];</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getStreamHeadersOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetStreamHeaders().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; stream_headers = 7 [json_name = "streamHeaders"];</code>
     */
    @java.lang.Override
    public java.lang.String getStreamHeadersOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetStreamHeaders().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearStreamHeaders() {
      bitField0_ = (bitField0_ & ~0x00000040);
      internalGetMutableStreamHeaders().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; stream_headers = 7 [json_name = "streamHeaders"];</code>
     */
    public Builder removeStreamHeaders(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableStreamHeaders().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableStreamHeaders() {
      bitField0_ |= 0x00000040;
      return internalGetMutableStreamHeaders().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; stream_headers = 7 [json_name = "streamHeaders"];</code>
     */
    public Builder putStreamHeaders(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableStreamHeaders().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; stream_headers = 7 [json_name = "streamHeaders"];</code>
     */
    public Builder putAllStreamHeaders(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableStreamHeaders().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000040;
      return this;
    }

    // @@protoc_insertion_point(builder_scope:stream.v1.CreateChannelRequest)
  }

  // @@protoc_insertion_point(class_scope:stream.v1.CreateChannelRequest)
  private static final com.stream.v1.CreateChannelRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.stream.v1.CreateChannelRequest();
  }

  public static com.stream.v1.CreateChannelRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateChannelRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateChannelRequest>() {
    @java.lang.Override
    public CreateChannelRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateChannelRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateChannelRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.stream.v1.CreateChannelRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

