// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/pairing.proto
// Protobuf Java Version: 4.29.0

package com.stream.v1;

public interface CredentialSummaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.v1.CredentialSummary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string label = 1 [json_name = "label"];</code>
   * @return The label.
   */
  java.lang.String getLabel();
  /**
   * <code>string label = 1 [json_name = "label"];</code>
   * @return The bytes for label.
   */
  com.google.protobuf.ByteString
      getLabelBytes();

  /**
   * <code>.google.protobuf.Timestamp created_at = 2 [json_name = "createdAt"];</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 2 [json_name = "createdAt"];</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 2 [json_name = "createdAt"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

  /**
   * <code>optional .google.protobuf.Timestamp revoked_at = 3 [json_name = "revokedAt"];</code>
   * @return Whether the revokedAt field is set.
   */
  boolean hasRevokedAt();
  /**
   * <code>optional .google.protobuf.Timestamp revoked_at = 3 [json_name = "revokedAt"];</code>
   * @return The revokedAt.
   */
  com.google.protobuf.Timestamp getRevokedAt();
  /**
   * <code>optional .google.protobuf.Timestamp revoked_at = 3 [json_name = "revokedAt"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getRevokedAtOrBuilder();
}
