// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/discovery.proto
// Protobuf Java Version: 4.29.0

package com.stream.v1;

public final class DiscoveryProto {
  private DiscoveryProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      DiscoveryProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stream_v1_DiscoveryStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_stream_v1_DiscoveryStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stream_v1_UnmatchedLink_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_stream_v1_UnmatchedLink_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stream_v1_GetUnmatchedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_stream_v1_GetUnmatchedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stream_v1_UnmatchedResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_stream_v1_UnmatchedResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031stream/v1/discovery.proto\022\tstream.v1\032\037" +
      "google/protobuf/timestamp.proto\"\323\001\n\027Disc" +
      "overyStatusResponse\022:\n\010last_run\030\001 \001(\0132\032." +
      "google.protobuf.TimestampH\000R\007lastRun\210\001\001\022" +
      "\037\n\013found_today\030\002 \001(\005R\nfoundToday\022%\n\016prom" +
      "oted_today\030\003 \001(\005R\rpromotedToday\022\'\n\017unmat" +
      "ched_count\030\004 \001(\005R\016unmatchedCountB\013\n\t_las" +
      "t_run\"Z\n\rUnmatchedLink\022\020\n\003url\030\001 \001(\tR\003url" +
      "\022\035\n\nsource_url\030\002 \001(\tR\tsourceUrl\022\030\n\007conte" +
      "xt\030\003 \001(\tR\007context\":\n\023GetUnmatchedRequest" +
      "\022\031\n\005limit\030\001 \001(\005H\000R\005limit\210\001\001B\010\n\006_limit\"a\n" +
      "\021UnmatchedResponse\0226\n\tunmatched\030\001 \003(\0132\030." +
      "stream.v1.UnmatchedLinkR\tunmatched\022\024\n\005to" +
      "tal\030\002 \001(\005R\005totalB\253\001\n\rcom.stream.v1B\016Disc" +
      "overyProtoP\001ZEgithub.com/fredrick-karuri" +
      "/nativestream/sdk-gen/go/stream/v1;strea" +
      "mv1\242\002\003SXX\252\002\tStream.V1\312\002\tStream\\V1\342\002\025Stre" +
      "am\\V1\\GPBMetadata\352\002\nStream::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_stream_v1_DiscoveryStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_stream_v1_DiscoveryStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_stream_v1_DiscoveryStatusResponse_descriptor,
        new java.lang.String[] { "LastRun", "FoundToday", "PromotedToday", "UnmatchedCount", });
    internal_static_stream_v1_UnmatchedLink_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_stream_v1_UnmatchedLink_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_stream_v1_UnmatchedLink_descriptor,
        new java.lang.String[] { "Url", "SourceUrl", "Context", });
    internal_static_stream_v1_GetUnmatchedRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_stream_v1_GetUnmatchedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_stream_v1_GetUnmatchedRequest_descriptor,
        new java.lang.String[] { "Limit", });
    internal_static_stream_v1_UnmatchedResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_stream_v1_UnmatchedResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_stream_v1_UnmatchedResponse_descriptor,
        new java.lang.String[] { "Unmatched", "Total", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
