// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/discovery.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.stream.v1;

@kotlin.jvm.JvmName("-initializediscoveryStatusResponse")
public inline fun discoveryStatusResponse(block: com.stream.v1.DiscoveryStatusResponseKt.Dsl.() -> kotlin.Unit): com.stream.v1.DiscoveryStatusResponse =
  com.stream.v1.DiscoveryStatusResponseKt.Dsl._create(com.stream.v1.DiscoveryStatusResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 * Response for GET /api/discovery/status.
 * ```
 *
 * Protobuf type `stream.v1.DiscoveryStatusResponse`
 */
public object DiscoveryStatusResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.stream.v1.DiscoveryStatusResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.stream.v1.DiscoveryStatusResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.stream.v1.DiscoveryStatusResponse = _builder.build()

    /**
     * `optional .google.protobuf.Timestamp last_run = 1 [json_name = "lastRun"];`
     */
    public var lastRun: com.google.protobuf.Timestamp
      @JvmName("getLastRun")
      get() = _builder.lastRun
      @JvmName("setLastRun")
      set(value) {
        _builder.lastRun = value
      }
    /**
     * `optional .google.protobuf.Timestamp last_run = 1 [json_name = "lastRun"];`
     */
    public fun clearLastRun() {
      _builder.clearLastRun()
    }
    /**
     * `optional .google.protobuf.Timestamp last_run = 1 [json_name = "lastRun"];`
     * @return Whether the lastRun field is set.
     */
    public fun hasLastRun(): kotlin.Boolean {
      return _builder.hasLastRun()
    }

    public val DiscoveryStatusResponseKt.Dsl.lastRunOrNull: com.google.protobuf.Timestamp?
      get() = _builder.lastRunOrNull

    /**
     * `int32 found_today = 2 [json_name = "foundToday"];`
     */
    public var foundToday: kotlin.Int
      @JvmName("getFoundToday")
      get() = _builder.foundToday
      @JvmName("setFoundToday")
      set(value) {
        _builder.foundToday = value
      }
    /**
     * `int32 found_today = 2 [json_name = "foundToday"];`
     */
    public fun clearFoundToday() {
      _builder.clearFoundToday()
    }

    /**
     * `int32 promoted_today = 3 [json_name = "promotedToday"];`
     */
    public var promotedToday: kotlin.Int
      @JvmName("getPromotedToday")
      get() = _builder.promotedToday
      @JvmName("setPromotedToday")
      set(value) {
        _builder.promotedToday = value
      }
    /**
     * `int32 promoted_today = 3 [json_name = "promotedToday"];`
     */
    public fun clearPromotedToday() {
      _builder.clearPromotedToday()
    }

    /**
     * `int32 unmatched_count = 4 [json_name = "unmatchedCount"];`
     */
    public var unmatchedCount: kotlin.Int
      @JvmName("getUnmatchedCount")
      get() = _builder.unmatchedCount
      @JvmName("setUnmatchedCount")
      set(value) {
        _builder.unmatchedCount = value
      }
    /**
     * `int32 unmatched_count = 4 [json_name = "unmatchedCount"];`
     */
    public fun clearUnmatchedCount() {
      _builder.clearUnmatchedCount()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.stream.v1.DiscoveryStatusResponse.copy(block: `com.stream.v1`.DiscoveryStatusResponseKt.Dsl.() -> kotlin.Unit): com.stream.v1.DiscoveryStatusResponse =
  `com.stream.v1`.DiscoveryStatusResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.stream.v1.DiscoveryStatusResponseOrBuilder.lastRunOrNull: com.google.protobuf.Timestamp?
  get() = if (hasLastRun()) getLastRun() else null

