// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/control.proto
// Protobuf Java Version: 4.29.0

package com.stream.v1;

public interface EnvelopeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.v1.Envelope)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.stream.v1.MessageType type = 1 [json_name = "type"];</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.stream.v1.MessageType type = 1 [json_name = "type"];</code>
   * @return The type.
   */
  com.stream.v1.MessageType getType();

  /**
   * <code>string from = 2 [json_name = "from"];</code>
   * @return The from.
   */
  java.lang.String getFrom();
  /**
   * <code>string from = 2 [json_name = "from"];</code>
   * @return The bytes for from.
   */
  com.google.protobuf.ByteString
      getFromBytes();

  /**
   * <code>string to = 3 [json_name = "to"];</code>
   * @return The to.
   */
  java.lang.String getTo();
  /**
   * <code>string to = 3 [json_name = "to"];</code>
   * @return The bytes for to.
   */
  com.google.protobuf.ByteString
      getToBytes();

  /**
   * <code>optional string auth = 4 [json_name = "auth"];</code>
   * @return Whether the auth field is set.
   */
  boolean hasAuth();
  /**
   * <code>optional string auth = 4 [json_name = "auth"];</code>
   * @return The auth.
   */
  java.lang.String getAuth();
  /**
   * <code>optional string auth = 4 [json_name = "auth"];</code>
   * @return The bytes for auth.
   */
  com.google.protobuf.ByteString
      getAuthBytes();

  /**
   * <code>string payload_json = 5 [json_name = "payloadJson"];</code>
   * @return The payloadJson.
   */
  java.lang.String getPayloadJson();
  /**
   * <code>string payload_json = 5 [json_name = "payloadJson"];</code>
   * @return The bytes for payloadJson.
   */
  com.google.protobuf.ByteString
      getPayloadJsonBytes();
}
