// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/control.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.stream.v1;

@kotlin.jvm.JvmName("-initializeenvelope")
public inline fun envelope(block: com.stream.v1.EnvelopeKt.Dsl.() -> kotlin.Unit): com.stream.v1.Envelope =
  com.stream.v1.EnvelopeKt.Dsl._create(com.stream.v1.Envelope.newBuilder()).apply { block() }._build()
/**
 * ```
 * Top-level wrapper for every LMC message.
 * to: device UUID for unicast, "broadcast" for all, "server" for hub-only.
 * auth: unset in zero-auth mode; populated for future token auth.
 * ```
 *
 * Protobuf type `stream.v1.Envelope`
 */
public object EnvelopeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.stream.v1.Envelope.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.stream.v1.Envelope.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.stream.v1.Envelope = _builder.build()

    /**
     * `.stream.v1.MessageType type = 1 [json_name = "type"];`
     */
    public var type: com.stream.v1.MessageType
      @JvmName("getType")
      get() = _builder.type
      @JvmName("setType")
      set(value) {
        _builder.type = value
      }
    public var typeValue: kotlin.Int
      @JvmName("getTypeValue")
      get() = _builder.typeValue
      @JvmName("setTypeValue")
      set(value) {
        _builder.typeValue = value
      }
    /**
     * `.stream.v1.MessageType type = 1 [json_name = "type"];`
     */
    public fun clearType() {
      _builder.clearType()
    }

    /**
     * `string from = 2 [json_name = "from"];`
     */
    public var from: kotlin.String
      @JvmName("getFrom")
      get() = _builder.from
      @JvmName("setFrom")
      set(value) {
        _builder.from = value
      }
    /**
     * `string from = 2 [json_name = "from"];`
     */
    public fun clearFrom() {
      _builder.clearFrom()
    }

    /**
     * `string to = 3 [json_name = "to"];`
     */
    public var to: kotlin.String
      @JvmName("getTo")
      get() = _builder.to
      @JvmName("setTo")
      set(value) {
        _builder.to = value
      }
    /**
     * `string to = 3 [json_name = "to"];`
     */
    public fun clearTo() {
      _builder.clearTo()
    }

    /**
     * `optional string auth = 4 [json_name = "auth"];`
     */
    public var auth: kotlin.String
      @JvmName("getAuth")
      get() = _builder.auth
      @JvmName("setAuth")
      set(value) {
        _builder.auth = value
      }
    /**
     * `optional string auth = 4 [json_name = "auth"];`
     */
    public fun clearAuth() {
      _builder.clearAuth()
    }
    /**
     * `optional string auth = 4 [json_name = "auth"];`
     * @return Whether the auth field is set.
     */
    public fun hasAuth(): kotlin.Boolean {
      return _builder.hasAuth()
    }

    /**
     * `.google.protobuf.Struct payload = 5 [json_name = "payload"];`
     */
    public var payload: com.google.protobuf.Struct
      @JvmName("getPayload")
      get() = _builder.payload
      @JvmName("setPayload")
      set(value) {
        _builder.payload = value
      }
    /**
     * `.google.protobuf.Struct payload = 5 [json_name = "payload"];`
     */
    public fun clearPayload() {
      _builder.clearPayload()
    }
    /**
     * `.google.protobuf.Struct payload = 5 [json_name = "payload"];`
     * @return Whether the payload field is set.
     */
    public fun hasPayload(): kotlin.Boolean {
      return _builder.hasPayload()
    }

    public val EnvelopeKt.Dsl.payloadOrNull: com.google.protobuf.Struct?
      get() = _builder.payloadOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.stream.v1.Envelope.copy(block: `com.stream.v1`.EnvelopeKt.Dsl.() -> kotlin.Unit): com.stream.v1.Envelope =
  `com.stream.v1`.EnvelopeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.stream.v1.EnvelopeOrBuilder.payloadOrNull: com.google.protobuf.Struct?
  get() = if (hasPayload()) getPayload() else null

