// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/api.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.stream.v1;

@kotlin.jvm.JvmName("-initializeerrorResponse")
public inline fun errorResponse(block: com.stream.v1.ErrorResponseKt.Dsl.() -> kotlin.Unit): com.stream.v1.ErrorResponse =
  com.stream.v1.ErrorResponseKt.Dsl._create(com.stream.v1.ErrorResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `stream.v1.ErrorResponse`
 */
public object ErrorResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.stream.v1.ErrorResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.stream.v1.ErrorResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.stream.v1.ErrorResponse = _builder.build()

    /**
     * `string error = 1 [json_name = "error"];`
     */
    public var error: kotlin.String
      @JvmName("getError")
      get() = _builder.error
      @JvmName("setError")
      set(value) {
        _builder.error = value
      }
    /**
     * `string error = 1 [json_name = "error"];`
     */
    public fun clearError() {
      _builder.clearError()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.stream.v1.ErrorResponse.copy(block: `com.stream.v1`.ErrorResponseKt.Dsl.() -> kotlin.Unit): com.stream.v1.ErrorResponse =
  `com.stream.v1`.ErrorResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

