// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/discovery.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.stream.v1;

@kotlin.jvm.JvmName("-initializegetUnmatchedRequest")
public inline fun getUnmatchedRequest(block: com.stream.v1.GetUnmatchedRequestKt.Dsl.() -> kotlin.Unit): com.stream.v1.GetUnmatchedRequest =
  com.stream.v1.GetUnmatchedRequestKt.Dsl._create(com.stream.v1.GetUnmatchedRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * Request for GET /api/discovery/unmatched.
 * limit: max number of results to return; server defaults to 50 if unset.
 * ```
 *
 * Protobuf type `stream.v1.GetUnmatchedRequest`
 */
public object GetUnmatchedRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.stream.v1.GetUnmatchedRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.stream.v1.GetUnmatchedRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.stream.v1.GetUnmatchedRequest = _builder.build()

    /**
     * `optional int32 limit = 1 [json_name = "limit"];`
     */
    public var limit: kotlin.Int
      @JvmName("getLimit")
      get() = _builder.limit
      @JvmName("setLimit")
      set(value) {
        _builder.limit = value
      }
    /**
     * `optional int32 limit = 1 [json_name = "limit"];`
     */
    public fun clearLimit() {
      _builder.clearLimit()
    }
    /**
     * `optional int32 limit = 1 [json_name = "limit"];`
     * @return Whether the limit field is set.
     */
    public fun hasLimit(): kotlin.Boolean {
      return _builder.hasLimit()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.stream.v1.GetUnmatchedRequest.copy(block: `com.stream.v1`.GetUnmatchedRequestKt.Dsl.() -> kotlin.Unit): com.stream.v1.GetUnmatchedRequest =
  `com.stream.v1`.GetUnmatchedRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

