// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/discovery.proto
// Protobuf Java Version: 4.29.0

package com.stream.v1;

public interface GetUnmatchedRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.v1.GetUnmatchedRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 limit = 1 [json_name = "limit"];</code>
   * @return Whether the limit field is set.
   */
  boolean hasLimit();
  /**
   * <code>optional int32 limit = 1 [json_name = "limit"];</code>
   * @return The limit.
   */
  int getLimit();
}
