// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/api.proto
// Protobuf Java Version: 4.29.0

package com.stream.v1;

public interface LinkScoreResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.v1.LinkScoreResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string url = 1 [json_name = "url"];</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 1 [json_name = "url"];</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>double score = 2 [json_name = "score"];</code>
   * @return The score.
   */
  double getScore();

  /**
   * <code>int32 latency_ms = 3 [json_name = "latencyMs"];</code>
   * @return The latencyMs.
   */
  int getLatencyMs();

  /**
   * <code>string state = 4 [json_name = "state"];</code>
   * @return The state.
   */
  java.lang.String getState();
  /**
   * <code>string state = 4 [json_name = "state"];</code>
   * @return The bytes for state.
   */
  com.google.protobuf.ByteString
      getStateBytes();

  /**
   * <code>int32 fail_count = 5 [json_name = "failCount"];</code>
   * @return The failCount.
   */
  int getFailCount();

  /**
   * <code>map&lt;string, string&gt; headers = 6 [json_name = "headers"];</code>
   */
  int getHeadersCount();
  /**
   * <code>map&lt;string, string&gt; headers = 6 [json_name = "headers"];</code>
   */
  boolean containsHeaders(
      java.lang.String key);
  /**
   * Use {@link #getHeadersMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getHeaders();
  /**
   * <code>map&lt;string, string&gt; headers = 6 [json_name = "headers"];</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getHeadersMap();
  /**
   * <code>map&lt;string, string&gt; headers = 6 [json_name = "headers"];</code>
   */
  /* nullable */
java.lang.String getHeadersOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; headers = 6 [json_name = "headers"];</code>
   */
  java.lang.String getHeadersOrThrow(
      java.lang.String key);

  /**
   * <code>optional string failure_reason = 7 [json_name = "failureReason"];</code>
   * @return Whether the failureReason field is set.
   */
  boolean hasFailureReason();
  /**
   * <code>optional string failure_reason = 7 [json_name = "failureReason"];</code>
   * @return The failureReason.
   */
  java.lang.String getFailureReason();
  /**
   * <code>optional string failure_reason = 7 [json_name = "failureReason"];</code>
   * @return The bytes for failureReason.
   */
  com.google.protobuf.ByteString
      getFailureReasonBytes();
}
