// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/api.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.stream.v1;

@kotlin.jvm.JvmName("-initializelinkScoreResponse")
public inline fun linkScoreResponse(block: com.stream.v1.LinkScoreResponseKt.Dsl.() -> kotlin.Unit): com.stream.v1.LinkScoreResponse =
  com.stream.v1.LinkScoreResponseKt.Dsl._create(com.stream.v1.LinkScoreResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `stream.v1.LinkScoreResponse`
 */
public object LinkScoreResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.stream.v1.LinkScoreResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.stream.v1.LinkScoreResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.stream.v1.LinkScoreResponse = _builder.build()

    /**
     * `string url = 1 [json_name = "url"];`
     */
    public var url: kotlin.String
      @JvmName("getUrl")
      get() = _builder.url
      @JvmName("setUrl")
      set(value) {
        _builder.url = value
      }
    /**
     * `string url = 1 [json_name = "url"];`
     */
    public fun clearUrl() {
      _builder.clearUrl()
    }

    /**
     * `double score = 2 [json_name = "score"];`
     */
    public var score: kotlin.Double
      @JvmName("getScore")
      get() = _builder.score
      @JvmName("setScore")
      set(value) {
        _builder.score = value
      }
    /**
     * `double score = 2 [json_name = "score"];`
     */
    public fun clearScore() {
      _builder.clearScore()
    }

    /**
     * `int32 latency_ms = 3 [json_name = "latencyMs"];`
     */
    public var latencyMs: kotlin.Int
      @JvmName("getLatencyMs")
      get() = _builder.latencyMs
      @JvmName("setLatencyMs")
      set(value) {
        _builder.latencyMs = value
      }
    /**
     * `int32 latency_ms = 3 [json_name = "latencyMs"];`
     */
    public fun clearLatencyMs() {
      _builder.clearLatencyMs()
    }

    /**
     * `string state = 4 [json_name = "state"];`
     */
    public var state: kotlin.String
      @JvmName("getState")
      get() = _builder.state
      @JvmName("setState")
      set(value) {
        _builder.state = value
      }
    /**
     * `string state = 4 [json_name = "state"];`
     */
    public fun clearState() {
      _builder.clearState()
    }

    /**
     * `int32 fail_count = 5 [json_name = "failCount"];`
     */
    public var failCount: kotlin.Int
      @JvmName("getFailCount")
      get() = _builder.failCount
      @JvmName("setFailCount")
      set(value) {
        _builder.failCount = value
      }
    /**
     * `int32 fail_count = 5 [json_name = "failCount"];`
     */
    public fun clearFailCount() {
      _builder.clearFailCount()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class HeadersProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `map<string, string> headers = 6 [json_name = "headers"];`
     */
     public val headers: com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, HeadersProxy>
      @kotlin.jvm.JvmSynthetic
      @JvmName("getHeadersMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.headersMap
      )
    /**
     * `map<string, string> headers = 6 [json_name = "headers"];`
     */
    @JvmName("putHeaders")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, HeadersProxy>
      .put(key: kotlin.String, value: kotlin.String) {
         _builder.putHeaders(key, value)
       }
    /**
     * `map<string, string> headers = 6 [json_name = "headers"];`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("setHeaders")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, HeadersProxy>
      .set(key: kotlin.String, value: kotlin.String) {
         put(key, value)
       }
    /**
     * `map<string, string> headers = 6 [json_name = "headers"];`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("removeHeaders")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, HeadersProxy>
      .remove(key: kotlin.String) {
         _builder.removeHeaders(key)
       }
    /**
     * `map<string, string> headers = 6 [json_name = "headers"];`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("putAllHeaders")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, HeadersProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, kotlin.String>) {
         _builder.putAllHeaders(map)
       }
    /**
     * `map<string, string> headers = 6 [json_name = "headers"];`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("clearHeaders")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, HeadersProxy>
      .clear() {
         _builder.clearHeaders()
       }

    /**
     * `optional string failure_reason = 7 [json_name = "failureReason"];`
     */
    public var failureReason: kotlin.String
      @JvmName("getFailureReason")
      get() = _builder.failureReason
      @JvmName("setFailureReason")
      set(value) {
        _builder.failureReason = value
      }
    /**
     * `optional string failure_reason = 7 [json_name = "failureReason"];`
     */
    public fun clearFailureReason() {
      _builder.clearFailureReason()
    }
    /**
     * `optional string failure_reason = 7 [json_name = "failureReason"];`
     * @return Whether the failureReason field is set.
     */
    public fun hasFailureReason(): kotlin.Boolean {
      return _builder.hasFailureReason()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.stream.v1.LinkScoreResponse.copy(block: `com.stream.v1`.LinkScoreResponseKt.Dsl.() -> kotlin.Unit): com.stream.v1.LinkScoreResponse =
  `com.stream.v1`.LinkScoreResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

