// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/pairing.proto
// Protobuf Java Version: 4.29.0

package com.stream.v1;

public interface PairApproveRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.v1.PairApproveRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string label = 1 [json_name = "label"];</code>
   * @return The label.
   */
  java.lang.String getLabel();
  /**
   * <code>string label = 1 [json_name = "label"];</code>
   * @return The bytes for label.
   */
  com.google.protobuf.ByteString
      getLabelBytes();
}
