// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/pairing.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.stream.v1;

@kotlin.jvm.JvmName("-initializepairStatusResponse")
public inline fun pairStatusResponse(block: com.stream.v1.PairStatusResponseKt.Dsl.() -> kotlin.Unit): com.stream.v1.PairStatusResponse =
  com.stream.v1.PairStatusResponseKt.Dsl._create(com.stream.v1.PairStatusResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 * PairStatusResponse is returned to a device polling its own session.
 * token and label are populated only once status is "approved".
 * ```
 *
 * Protobuf type `stream.v1.PairStatusResponse`
 */
public object PairStatusResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.stream.v1.PairStatusResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.stream.v1.PairStatusResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.stream.v1.PairStatusResponse = _builder.build()

    /**
     * `string status = 1 [json_name = "status"];`
     */
    public var status: kotlin.String
      @JvmName("getStatus")
      get() = _builder.status
      @JvmName("setStatus")
      set(value) {
        _builder.status = value
      }
    /**
     * `string status = 1 [json_name = "status"];`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * `optional string token = 2 [json_name = "token"];`
     */
    public var token: kotlin.String
      @JvmName("getToken")
      get() = _builder.token
      @JvmName("setToken")
      set(value) {
        _builder.token = value
      }
    /**
     * `optional string token = 2 [json_name = "token"];`
     */
    public fun clearToken() {
      _builder.clearToken()
    }
    /**
     * `optional string token = 2 [json_name = "token"];`
     * @return Whether the token field is set.
     */
    public fun hasToken(): kotlin.Boolean {
      return _builder.hasToken()
    }

    /**
     * `optional string label = 3 [json_name = "label"];`
     */
    public var label: kotlin.String
      @JvmName("getLabel")
      get() = _builder.label
      @JvmName("setLabel")
      set(value) {
        _builder.label = value
      }
    /**
     * `optional string label = 3 [json_name = "label"];`
     */
    public fun clearLabel() {
      _builder.clearLabel()
    }
    /**
     * `optional string label = 3 [json_name = "label"];`
     * @return Whether the label field is set.
     */
    public fun hasLabel(): kotlin.Boolean {
      return _builder.hasLabel()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.stream.v1.PairStatusResponse.copy(block: `com.stream.v1`.PairStatusResponseKt.Dsl.() -> kotlin.Unit): com.stream.v1.PairStatusResponse =
  `com.stream.v1`.PairStatusResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

