// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/pairing.proto
// Protobuf Java Version: 4.29.0

package com.stream.v1;

public interface PairStartResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.v1.PairStartResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string session_id = 1 [json_name = "sessionId"];</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 1 [json_name = "sessionId"];</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>string code = 2 [json_name = "code"];</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 2 [json_name = "code"];</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>int32 expires_in_seconds = 3 [json_name = "expiresInSeconds"];</code>
   * @return The expiresInSeconds.
   */
  int getExpiresInSeconds();
}
