// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/pairing.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.stream.v1;

@kotlin.jvm.JvmName("-initializepairStartResponse")
public inline fun pairStartResponse(block: com.stream.v1.PairStartResponseKt.Dsl.() -> kotlin.Unit): com.stream.v1.PairStartResponse =
  com.stream.v1.PairStartResponseKt.Dsl._create(com.stream.v1.PairStartResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `stream.v1.PairStartResponse`
 */
public object PairStartResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.stream.v1.PairStartResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.stream.v1.PairStartResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.stream.v1.PairStartResponse = _builder.build()

    /**
     * `string session_id = 1 [json_name = "sessionId"];`
     */
    public var sessionId: kotlin.String
      @JvmName("getSessionId")
      get() = _builder.sessionId
      @JvmName("setSessionId")
      set(value) {
        _builder.sessionId = value
      }
    /**
     * `string session_id = 1 [json_name = "sessionId"];`
     */
    public fun clearSessionId() {
      _builder.clearSessionId()
    }

    /**
     * `string code = 2 [json_name = "code"];`
     */
    public var code: kotlin.String
      @JvmName("getCode")
      get() = _builder.code
      @JvmName("setCode")
      set(value) {
        _builder.code = value
      }
    /**
     * `string code = 2 [json_name = "code"];`
     */
    public fun clearCode() {
      _builder.clearCode()
    }

    /**
     * `int32 expires_in_seconds = 3 [json_name = "expiresInSeconds"];`
     */
    public var expiresInSeconds: kotlin.Int
      @JvmName("getExpiresInSeconds")
      get() = _builder.expiresInSeconds
      @JvmName("setExpiresInSeconds")
      set(value) {
        _builder.expiresInSeconds = value
      }
    /**
     * `int32 expires_in_seconds = 3 [json_name = "expiresInSeconds"];`
     */
    public fun clearExpiresInSeconds() {
      _builder.clearExpiresInSeconds()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.stream.v1.PairStartResponse.copy(block: `com.stream.v1`.PairStartResponseKt.Dsl.() -> kotlin.Unit): com.stream.v1.PairStartResponse =
  `com.stream.v1`.PairStartResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

