// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/pairing.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.stream.v1;

@kotlin.jvm.JvmName("-initializepairApproveResponse")
public inline fun pairApproveResponse(block: com.stream.v1.PairApproveResponseKt.Dsl.() -> kotlin.Unit): com.stream.v1.PairApproveResponse =
  com.stream.v1.PairApproveResponseKt.Dsl._create(com.stream.v1.PairApproveResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `stream.v1.PairApproveResponse`
 */
public object PairApproveResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.stream.v1.PairApproveResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.stream.v1.PairApproveResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.stream.v1.PairApproveResponse = _builder.build()

    /**
     * `string session_id = 1 [json_name = "sessionId"];`
     */
    public var sessionId: kotlin.String
      @JvmName("getSessionId")
      get() = _builder.sessionId
      @JvmName("setSessionId")
      set(value) {
        _builder.sessionId = value
      }
    /**
     * `string session_id = 1 [json_name = "sessionId"];`
     */
    public fun clearSessionId() {
      _builder.clearSessionId()
    }

    /**
     * `string status = 2 [json_name = "status"];`
     */
    public var status: kotlin.String
      @JvmName("getStatus")
      get() = _builder.status
      @JvmName("setStatus")
      set(value) {
        _builder.status = value
      }
    /**
     * `string status = 2 [json_name = "status"];`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.stream.v1.PairApproveResponse.copy(block: `com.stream.v1`.PairApproveResponseKt.Dsl.() -> kotlin.Unit): com.stream.v1.PairApproveResponse =
  `com.stream.v1`.PairApproveResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

