// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/pairing.proto
// Protobuf Java Version: 4.29.0

package com.stream.v1;

public interface PairStartRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.v1.PairStartRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string platform = 1 [json_name = "platform"];</code>
   * @return The platform.
   */
  java.lang.String getPlatform();
  /**
   * <code>string platform = 1 [json_name = "platform"];</code>
   * @return The bytes for platform.
   */
  com.google.protobuf.ByteString
      getPlatformBytes();
}
