// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/config.proto
// Protobuf Java Version: 4.29.0

package com.stream.v1;

public interface ProxyConfigResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.v1.ProxyConfigResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool enabled = 1 [json_name = "enabled"];</code>
   * @return The enabled.
   */
  boolean getEnabled();
}
