// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/config.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.stream.v1;

@kotlin.jvm.JvmName("-initializeproxyConfigResponse")
public inline fun proxyConfigResponse(block: com.stream.v1.ProxyConfigResponseKt.Dsl.() -> kotlin.Unit): com.stream.v1.ProxyConfigResponse =
  com.stream.v1.ProxyConfigResponseKt.Dsl._create(com.stream.v1.ProxyConfigResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 * Shared response shape for GET and PUT /api/proxy/config.
 * ```
 *
 * Protobuf type `stream.v1.ProxyConfigResponse`
 */
public object ProxyConfigResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.stream.v1.ProxyConfigResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.stream.v1.ProxyConfigResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.stream.v1.ProxyConfigResponse = _builder.build()

    /**
     * `bool enabled = 1 [json_name = "enabled"];`
     */
    public var enabled: kotlin.Boolean
      @JvmName("getEnabled")
      get() = _builder.enabled
      @JvmName("setEnabled")
      set(value) {
        _builder.enabled = value
      }
    /**
     * `bool enabled = 1 [json_name = "enabled"];`
     */
    public fun clearEnabled() {
      _builder.clearEnabled()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.stream.v1.ProxyConfigResponse.copy(block: `com.stream.v1`.ProxyConfigResponseKt.Dsl.() -> kotlin.Unit): com.stream.v1.ProxyConfigResponse =
  `com.stream.v1`.ProxyConfigResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

