// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/control.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.stream.v1;

@kotlin.jvm.JvmName("-initializepullBackPayload")
public inline fun pullBackPayload(block: com.stream.v1.PullBackPayloadKt.Dsl.() -> kotlin.Unit): com.stream.v1.PullBackPayload =
  com.stream.v1.PullBackPayloadKt.Dsl._create(com.stream.v1.PullBackPayload.newBuilder()).apply { block() }._build()
/**
 * ```
 * Sent by a controller to request the target's stream.
 * ```
 *
 * Protobuf type `stream.v1.PullBackPayload`
 */
public object PullBackPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.stream.v1.PullBackPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.stream.v1.PullBackPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.stream.v1.PullBackPayload = _builder.build()

    /**
     * `string from_device = 1 [json_name = "fromDevice"];`
     */
    public var fromDevice: kotlin.String
      @JvmName("getFromDevice")
      get() = _builder.fromDevice
      @JvmName("setFromDevice")
      set(value) {
        _builder.fromDevice = value
      }
    /**
     * `string from_device = 1 [json_name = "fromDevice"];`
     */
    public fun clearFromDevice() {
      _builder.clearFromDevice()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.stream.v1.PullBackPayload.copy(block: `com.stream.v1`.PullBackPayloadKt.Dsl.() -> kotlin.Unit): com.stream.v1.PullBackPayload =
  `com.stream.v1`.PullBackPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

