// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/control.proto
// Protobuf Java Version: 4.29.0

package com.stream.v1;

/**
 * <pre>
 * Sent by a controller to request the target's stream.
 * </pre>
 *
 * Protobuf type {@code stream.v1.PullBackPayload}
 */
public final class PullBackPayload extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:stream.v1.PullBackPayload)
    PullBackPayloadOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      PullBackPayload.class.getName());
  }
  // Use PullBackPayload.newBuilder() to construct.
  private PullBackPayload(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PullBackPayload() {
    fromDevice_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.stream.v1.ControlProto.internal_static_stream_v1_PullBackPayload_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.stream.v1.ControlProto.internal_static_stream_v1_PullBackPayload_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.stream.v1.PullBackPayload.class, com.stream.v1.PullBackPayload.Builder.class);
  }

  public static final int FROM_DEVICE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object fromDevice_ = "";
  /**
   * <code>string from_device = 1 [json_name = "fromDevice"];</code>
   * @return The fromDevice.
   */
  @java.lang.Override
  public java.lang.String getFromDevice() {
    java.lang.Object ref = fromDevice_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fromDevice_ = s;
      return s;
    }
  }
  /**
   * <code>string from_device = 1 [json_name = "fromDevice"];</code>
   * @return The bytes for fromDevice.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFromDeviceBytes() {
    java.lang.Object ref = fromDevice_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fromDevice_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(fromDevice_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, fromDevice_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(fromDevice_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, fromDevice_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.stream.v1.PullBackPayload)) {
      return super.equals(obj);
    }
    com.stream.v1.PullBackPayload other = (com.stream.v1.PullBackPayload) obj;

    if (!getFromDevice()
        .equals(other.getFromDevice())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FROM_DEVICE_FIELD_NUMBER;
    hash = (53 * hash) + getFromDevice().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.stream.v1.PullBackPayload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stream.v1.PullBackPayload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stream.v1.PullBackPayload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stream.v1.PullBackPayload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stream.v1.PullBackPayload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stream.v1.PullBackPayload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stream.v1.PullBackPayload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.stream.v1.PullBackPayload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.stream.v1.PullBackPayload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.stream.v1.PullBackPayload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stream.v1.PullBackPayload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.stream.v1.PullBackPayload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.stream.v1.PullBackPayload prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Sent by a controller to request the target's stream.
   * </pre>
   *
   * Protobuf type {@code stream.v1.PullBackPayload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:stream.v1.PullBackPayload)
      com.stream.v1.PullBackPayloadOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stream.v1.ControlProto.internal_static_stream_v1_PullBackPayload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stream.v1.ControlProto.internal_static_stream_v1_PullBackPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stream.v1.PullBackPayload.class, com.stream.v1.PullBackPayload.Builder.class);
    }

    // Construct using com.stream.v1.PullBackPayload.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      fromDevice_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.stream.v1.ControlProto.internal_static_stream_v1_PullBackPayload_descriptor;
    }

    @java.lang.Override
    public com.stream.v1.PullBackPayload getDefaultInstanceForType() {
      return com.stream.v1.PullBackPayload.getDefaultInstance();
    }

    @java.lang.Override
    public com.stream.v1.PullBackPayload build() {
      com.stream.v1.PullBackPayload result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.stream.v1.PullBackPayload buildPartial() {
      com.stream.v1.PullBackPayload result = new com.stream.v1.PullBackPayload(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.stream.v1.PullBackPayload result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.fromDevice_ = fromDevice_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.stream.v1.PullBackPayload) {
        return mergeFrom((com.stream.v1.PullBackPayload)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.stream.v1.PullBackPayload other) {
      if (other == com.stream.v1.PullBackPayload.getDefaultInstance()) return this;
      if (!other.getFromDevice().isEmpty()) {
        fromDevice_ = other.fromDevice_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              fromDevice_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object fromDevice_ = "";
    /**
     * <code>string from_device = 1 [json_name = "fromDevice"];</code>
     * @return The fromDevice.
     */
    public java.lang.String getFromDevice() {
      java.lang.Object ref = fromDevice_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromDevice_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string from_device = 1 [json_name = "fromDevice"];</code>
     * @return The bytes for fromDevice.
     */
    public com.google.protobuf.ByteString
        getFromDeviceBytes() {
      java.lang.Object ref = fromDevice_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromDevice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string from_device = 1 [json_name = "fromDevice"];</code>
     * @param value The fromDevice to set.
     * @return This builder for chaining.
     */
    public Builder setFromDevice(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      fromDevice_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string from_device = 1 [json_name = "fromDevice"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFromDevice() {
      fromDevice_ = getDefaultInstance().getFromDevice();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string from_device = 1 [json_name = "fromDevice"];</code>
     * @param value The bytes for fromDevice to set.
     * @return This builder for chaining.
     */
    public Builder setFromDeviceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      fromDevice_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:stream.v1.PullBackPayload)
  }

  // @@protoc_insertion_point(class_scope:stream.v1.PullBackPayload)
  private static final com.stream.v1.PullBackPayload DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.stream.v1.PullBackPayload();
  }

  public static com.stream.v1.PullBackPayload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PullBackPayload>
      PARSER = new com.google.protobuf.AbstractParser<PullBackPayload>() {
    @java.lang.Override
    public PullBackPayload parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PullBackPayload> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PullBackPayload> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.stream.v1.PullBackPayload getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

