// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/control.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.stream.v1;

@kotlin.jvm.JvmName("-initializeregisterPayload")
public inline fun registerPayload(block: com.stream.v1.RegisterPayloadKt.Dsl.() -> kotlin.Unit): com.stream.v1.RegisterPayload =
  com.stream.v1.RegisterPayloadKt.Dsl._create(com.stream.v1.RegisterPayload.newBuilder()).apply { block() }._build()
/**
 * ```
 * Sent by a device immediately after connecting.
 * ```
 *
 * Protobuf type `stream.v1.RegisterPayload`
 */
public object RegisterPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.stream.v1.RegisterPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.stream.v1.RegisterPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.stream.v1.RegisterPayload = _builder.build()

    /**
     * `string name = 1 [json_name = "name"];`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.name
      @JvmName("setName")
      set(value) {
        _builder.name = value
      }
    /**
     * `string name = 1 [json_name = "name"];`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `.stream.v1.DeviceKind kind = 2 [json_name = "kind"];`
     */
    public var kind: com.stream.v1.DeviceKind
      @JvmName("getKind")
      get() = _builder.kind
      @JvmName("setKind")
      set(value) {
        _builder.kind = value
      }
    public var kindValue: kotlin.Int
      @JvmName("getKindValue")
      get() = _builder.kindValue
      @JvmName("setKindValue")
      set(value) {
        _builder.kindValue = value
      }
    /**
     * `.stream.v1.DeviceKind kind = 2 [json_name = "kind"];`
     */
    public fun clearKind() {
      _builder.clearKind()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.stream.v1.RegisterPayload.copy(block: `com.stream.v1`.RegisterPayloadKt.Dsl.() -> kotlin.Unit): com.stream.v1.RegisterPayload =
  `com.stream.v1`.RegisterPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

