// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/pairing.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.stream.v1;

@kotlin.jvm.JvmName("-initializerevokeCredentialRequest")
public inline fun revokeCredentialRequest(block: com.stream.v1.RevokeCredentialRequestKt.Dsl.() -> kotlin.Unit): com.stream.v1.RevokeCredentialRequest =
  com.stream.v1.RevokeCredentialRequestKt.Dsl._create(com.stream.v1.RevokeCredentialRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `stream.v1.RevokeCredentialRequest`
 */
public object RevokeCredentialRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.stream.v1.RevokeCredentialRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.stream.v1.RevokeCredentialRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.stream.v1.RevokeCredentialRequest = _builder.build()

    /**
     * `string label = 1 [json_name = "label"];`
     */
    public var label: kotlin.String
      @JvmName("getLabel")
      get() = _builder.label
      @JvmName("setLabel")
      set(value) {
        _builder.label = value
      }
    /**
     * `string label = 1 [json_name = "label"];`
     */
    public fun clearLabel() {
      _builder.clearLabel()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.stream.v1.RevokeCredentialRequest.copy(block: `com.stream.v1`.RevokeCredentialRequestKt.Dsl.() -> kotlin.Unit): com.stream.v1.RevokeCredentialRequest =
  `com.stream.v1`.RevokeCredentialRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

