// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/control.proto
// Protobuf Java Version: 4.29.0

package com.stream.v1;

public interface SessionListPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.v1.SessionListPayload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .stream.v1.SessionInfo sessions = 1 [json_name = "sessions"];</code>
   */
  java.util.List<com.stream.v1.SessionInfo> 
      getSessionsList();
  /**
   * <code>repeated .stream.v1.SessionInfo sessions = 1 [json_name = "sessions"];</code>
   */
  com.stream.v1.SessionInfo getSessions(int index);
  /**
   * <code>repeated .stream.v1.SessionInfo sessions = 1 [json_name = "sessions"];</code>
   */
  int getSessionsCount();
  /**
   * <code>repeated .stream.v1.SessionInfo sessions = 1 [json_name = "sessions"];</code>
   */
  java.util.List<? extends com.stream.v1.SessionInfoOrBuilder> 
      getSessionsOrBuilderList();
  /**
   * <code>repeated .stream.v1.SessionInfo sessions = 1 [json_name = "sessions"];</code>
   */
  com.stream.v1.SessionInfoOrBuilder getSessionsOrBuilder(
      int index);
}
