// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/control.proto
// Protobuf Java Version: 4.29.0

package com.stream.v1;

public interface SessionInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.v1.SessionInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string device_id = 1 [json_name = "deviceId"];</code>
   * @return The deviceId.
   */
  java.lang.String getDeviceId();
  /**
   * <code>string device_id = 1 [json_name = "deviceId"];</code>
   * @return The bytes for deviceId.
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.stream.v1.DeviceKind kind = 3 [json_name = "kind"];</code>
   * @return The enum numeric value on the wire for kind.
   */
  int getKindValue();
  /**
   * <code>.stream.v1.DeviceKind kind = 3 [json_name = "kind"];</code>
   * @return The kind.
   */
  com.stream.v1.DeviceKind getKind();

  /**
   * <code>string channel_id = 4 [json_name = "channelId"];</code>
   * @return The channelId.
   */
  java.lang.String getChannelId();
  /**
   * <code>string channel_id = 4 [json_name = "channelId"];</code>
   * @return The bytes for channelId.
   */
  com.google.protobuf.ByteString
      getChannelIdBytes();

  /**
   * <code>string channel_name = 5 [json_name = "channelName"];</code>
   * @return The channelName.
   */
  java.lang.String getChannelName();
  /**
   * <code>string channel_name = 5 [json_name = "channelName"];</code>
   * @return The bytes for channelName.
   */
  com.google.protobuf.ByteString
      getChannelNameBytes();

  /**
   * <code>string stream_url = 6 [json_name = "streamUrl"];</code>
   * @return The streamUrl.
   */
  java.lang.String getStreamUrl();
  /**
   * <code>string stream_url = 6 [json_name = "streamUrl"];</code>
   * @return The bytes for streamUrl.
   */
  com.google.protobuf.ByteString
      getStreamUrlBytes();

  /**
   * <code>bool playing = 7 [json_name = "playing"];</code>
   * @return The playing.
   */
  boolean getPlaying();

  /**
   * <code>double volume = 8 [json_name = "volume"];</code>
   * @return The volume.
   */
  double getVolume();

  /**
   * <code>.google.protobuf.Timestamp connected_at = 9 [json_name = "connectedAt"];</code>
   * @return Whether the connectedAt field is set.
   */
  boolean hasConnectedAt();
  /**
   * <code>.google.protobuf.Timestamp connected_at = 9 [json_name = "connectedAt"];</code>
   * @return The connectedAt.
   */
  com.google.protobuf.Timestamp getConnectedAt();
  /**
   * <code>.google.protobuf.Timestamp connected_at = 9 [json_name = "connectedAt"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getConnectedAtOrBuilder();
}
