// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/control.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.stream.v1;

@kotlin.jvm.JvmName("-initializestateUpdatePayload")
public inline fun stateUpdatePayload(block: com.stream.v1.StateUpdatePayloadKt.Dsl.() -> kotlin.Unit): com.stream.v1.StateUpdatePayload =
  com.stream.v1.StateUpdatePayloadKt.Dsl._create(com.stream.v1.StateUpdatePayload.newBuilder()).apply { block() }._build()
/**
 * ```
 * Broadcast by a target on every playback state change.
 * ```
 *
 * Protobuf type `stream.v1.StateUpdatePayload`
 */
public object StateUpdatePayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.stream.v1.StateUpdatePayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.stream.v1.StateUpdatePayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.stream.v1.StateUpdatePayload = _builder.build()

    /**
     * `string channel_id = 1 [json_name = "channelId"];`
     */
    public var channelId: kotlin.String
      @JvmName("getChannelId")
      get() = _builder.channelId
      @JvmName("setChannelId")
      set(value) {
        _builder.channelId = value
      }
    /**
     * `string channel_id = 1 [json_name = "channelId"];`
     */
    public fun clearChannelId() {
      _builder.clearChannelId()
    }

    /**
     * `string channel_name = 2 [json_name = "channelName"];`
     */
    public var channelName: kotlin.String
      @JvmName("getChannelName")
      get() = _builder.channelName
      @JvmName("setChannelName")
      set(value) {
        _builder.channelName = value
      }
    /**
     * `string channel_name = 2 [json_name = "channelName"];`
     */
    public fun clearChannelName() {
      _builder.clearChannelName()
    }

    /**
     * `string stream_url = 3 [json_name = "streamUrl"];`
     */
    public var streamUrl: kotlin.String
      @JvmName("getStreamUrl")
      get() = _builder.streamUrl
      @JvmName("setStreamUrl")
      set(value) {
        _builder.streamUrl = value
      }
    /**
     * `string stream_url = 3 [json_name = "streamUrl"];`
     */
    public fun clearStreamUrl() {
      _builder.clearStreamUrl()
    }

    /**
     * `bool playing = 4 [json_name = "playing"];`
     */
    public var playing: kotlin.Boolean
      @JvmName("getPlaying")
      get() = _builder.playing
      @JvmName("setPlaying")
      set(value) {
        _builder.playing = value
      }
    /**
     * `bool playing = 4 [json_name = "playing"];`
     */
    public fun clearPlaying() {
      _builder.clearPlaying()
    }

    /**
     * `double volume = 5 [json_name = "volume"];`
     */
    public var volume: kotlin.Double
      @JvmName("getVolume")
      get() = _builder.volume
      @JvmName("setVolume")
      set(value) {
        _builder.volume = value
      }
    /**
     * `double volume = 5 [json_name = "volume"];`
     */
    public fun clearVolume() {
      _builder.clearVolume()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.stream.v1.StateUpdatePayload.copy(block: `com.stream.v1`.StateUpdatePayloadKt.Dsl.() -> kotlin.Unit): com.stream.v1.StateUpdatePayload =
  `com.stream.v1`.StateUpdatePayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

