// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/api.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.stream.v1;

@kotlin.jvm.JvmName("-initializestatusResponse")
public inline fun statusResponse(block: com.stream.v1.StatusResponseKt.Dsl.() -> kotlin.Unit): com.stream.v1.StatusResponse =
  com.stream.v1.StatusResponseKt.Dsl._create(com.stream.v1.StatusResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `stream.v1.StatusResponse`
 */
public object StatusResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.stream.v1.StatusResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.stream.v1.StatusResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.stream.v1.StatusResponse = _builder.build()

    /**
     * `string status = 1 [json_name = "status"];`
     */
    public var status: kotlin.String
      @JvmName("getStatus")
      get() = _builder.status
      @JvmName("setStatus")
      set(value) {
        _builder.status = value
      }
    /**
     * `string status = 1 [json_name = "status"];`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.stream.v1.StatusResponse.copy(block: `com.stream.v1`.StatusResponseKt.Dsl.() -> kotlin.Unit): com.stream.v1.StatusResponse =
  `com.stream.v1`.StatusResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

