// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/discovery.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.stream.v1;

@kotlin.jvm.JvmName("-initializeunmatchedLink")
public inline fun unmatchedLink(block: com.stream.v1.UnmatchedLinkKt.Dsl.() -> kotlin.Unit): com.stream.v1.UnmatchedLink =
  com.stream.v1.UnmatchedLinkKt.Dsl._create(com.stream.v1.UnmatchedLink.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `stream.v1.UnmatchedLink`
 */
public object UnmatchedLinkKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.stream.v1.UnmatchedLink.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.stream.v1.UnmatchedLink.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.stream.v1.UnmatchedLink = _builder.build()

    /**
     * `string url = 1 [json_name = "url"];`
     */
    public var url: kotlin.String
      @JvmName("getUrl")
      get() = _builder.url
      @JvmName("setUrl")
      set(value) {
        _builder.url = value
      }
    /**
     * `string url = 1 [json_name = "url"];`
     */
    public fun clearUrl() {
      _builder.clearUrl()
    }

    /**
     * `string source_url = 2 [json_name = "sourceUrl"];`
     */
    public var sourceUrl: kotlin.String
      @JvmName("getSourceUrl")
      get() = _builder.sourceUrl
      @JvmName("setSourceUrl")
      set(value) {
        _builder.sourceUrl = value
      }
    /**
     * `string source_url = 2 [json_name = "sourceUrl"];`
     */
    public fun clearSourceUrl() {
      _builder.clearSourceUrl()
    }

    /**
     * `string context = 3 [json_name = "context"];`
     */
    public var context: kotlin.String
      @JvmName("getContext")
      get() = _builder.context
      @JvmName("setContext")
      set(value) {
        _builder.context = value
      }
    /**
     * `string context = 3 [json_name = "context"];`
     */
    public fun clearContext() {
      _builder.clearContext()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.stream.v1.UnmatchedLink.copy(block: `com.stream.v1`.UnmatchedLinkKt.Dsl.() -> kotlin.Unit): com.stream.v1.UnmatchedLink =
  `com.stream.v1`.UnmatchedLinkKt.Dsl._create(this.toBuilder()).apply { block() }._build()

