// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/discovery.proto
// Protobuf Java Version: 4.29.0

package com.stream.v1;

/**
 * <pre>
 * Response for GET /api/discovery/unmatched.
 * </pre>
 *
 * Protobuf type {@code stream.v1.UnmatchedResponse}
 */
public final class UnmatchedResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:stream.v1.UnmatchedResponse)
    UnmatchedResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      UnmatchedResponse.class.getName());
  }
  // Use UnmatchedResponse.newBuilder() to construct.
  private UnmatchedResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private UnmatchedResponse() {
    unmatched_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.stream.v1.DiscoveryProto.internal_static_stream_v1_UnmatchedResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.stream.v1.DiscoveryProto.internal_static_stream_v1_UnmatchedResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.stream.v1.UnmatchedResponse.class, com.stream.v1.UnmatchedResponse.Builder.class);
  }

  public static final int UNMATCHED_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.stream.v1.UnmatchedLink> unmatched_;
  /**
   * <code>repeated .stream.v1.UnmatchedLink unmatched = 1 [json_name = "unmatched"];</code>
   */
  @java.lang.Override
  public java.util.List<com.stream.v1.UnmatchedLink> getUnmatchedList() {
    return unmatched_;
  }
  /**
   * <code>repeated .stream.v1.UnmatchedLink unmatched = 1 [json_name = "unmatched"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.stream.v1.UnmatchedLinkOrBuilder> 
      getUnmatchedOrBuilderList() {
    return unmatched_;
  }
  /**
   * <code>repeated .stream.v1.UnmatchedLink unmatched = 1 [json_name = "unmatched"];</code>
   */
  @java.lang.Override
  public int getUnmatchedCount() {
    return unmatched_.size();
  }
  /**
   * <code>repeated .stream.v1.UnmatchedLink unmatched = 1 [json_name = "unmatched"];</code>
   */
  @java.lang.Override
  public com.stream.v1.UnmatchedLink getUnmatched(int index) {
    return unmatched_.get(index);
  }
  /**
   * <code>repeated .stream.v1.UnmatchedLink unmatched = 1 [json_name = "unmatched"];</code>
   */
  @java.lang.Override
  public com.stream.v1.UnmatchedLinkOrBuilder getUnmatchedOrBuilder(
      int index) {
    return unmatched_.get(index);
  }

  public static final int TOTAL_FIELD_NUMBER = 2;
  private int total_ = 0;
  /**
   * <code>int32 total = 2 [json_name = "total"];</code>
   * @return The total.
   */
  @java.lang.Override
  public int getTotal() {
    return total_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < unmatched_.size(); i++) {
      output.writeMessage(1, unmatched_.get(i));
    }
    if (total_ != 0) {
      output.writeInt32(2, total_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < unmatched_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, unmatched_.get(i));
    }
    if (total_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, total_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.stream.v1.UnmatchedResponse)) {
      return super.equals(obj);
    }
    com.stream.v1.UnmatchedResponse other = (com.stream.v1.UnmatchedResponse) obj;

    if (!getUnmatchedList()
        .equals(other.getUnmatchedList())) return false;
    if (getTotal()
        != other.getTotal()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getUnmatchedCount() > 0) {
      hash = (37 * hash) + UNMATCHED_FIELD_NUMBER;
      hash = (53 * hash) + getUnmatchedList().hashCode();
    }
    hash = (37 * hash) + TOTAL_FIELD_NUMBER;
    hash = (53 * hash) + getTotal();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.stream.v1.UnmatchedResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stream.v1.UnmatchedResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stream.v1.UnmatchedResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stream.v1.UnmatchedResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stream.v1.UnmatchedResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stream.v1.UnmatchedResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stream.v1.UnmatchedResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.stream.v1.UnmatchedResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.stream.v1.UnmatchedResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.stream.v1.UnmatchedResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stream.v1.UnmatchedResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.stream.v1.UnmatchedResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.stream.v1.UnmatchedResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Response for GET /api/discovery/unmatched.
   * </pre>
   *
   * Protobuf type {@code stream.v1.UnmatchedResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:stream.v1.UnmatchedResponse)
      com.stream.v1.UnmatchedResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stream.v1.DiscoveryProto.internal_static_stream_v1_UnmatchedResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stream.v1.DiscoveryProto.internal_static_stream_v1_UnmatchedResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stream.v1.UnmatchedResponse.class, com.stream.v1.UnmatchedResponse.Builder.class);
    }

    // Construct using com.stream.v1.UnmatchedResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (unmatchedBuilder_ == null) {
        unmatched_ = java.util.Collections.emptyList();
      } else {
        unmatched_ = null;
        unmatchedBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      total_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.stream.v1.DiscoveryProto.internal_static_stream_v1_UnmatchedResponse_descriptor;
    }

    @java.lang.Override
    public com.stream.v1.UnmatchedResponse getDefaultInstanceForType() {
      return com.stream.v1.UnmatchedResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.stream.v1.UnmatchedResponse build() {
      com.stream.v1.UnmatchedResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.stream.v1.UnmatchedResponse buildPartial() {
      com.stream.v1.UnmatchedResponse result = new com.stream.v1.UnmatchedResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.stream.v1.UnmatchedResponse result) {
      if (unmatchedBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          unmatched_ = java.util.Collections.unmodifiableList(unmatched_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.unmatched_ = unmatched_;
      } else {
        result.unmatched_ = unmatchedBuilder_.build();
      }
    }

    private void buildPartial0(com.stream.v1.UnmatchedResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.total_ = total_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.stream.v1.UnmatchedResponse) {
        return mergeFrom((com.stream.v1.UnmatchedResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.stream.v1.UnmatchedResponse other) {
      if (other == com.stream.v1.UnmatchedResponse.getDefaultInstance()) return this;
      if (unmatchedBuilder_ == null) {
        if (!other.unmatched_.isEmpty()) {
          if (unmatched_.isEmpty()) {
            unmatched_ = other.unmatched_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUnmatchedIsMutable();
            unmatched_.addAll(other.unmatched_);
          }
          onChanged();
        }
      } else {
        if (!other.unmatched_.isEmpty()) {
          if (unmatchedBuilder_.isEmpty()) {
            unmatchedBuilder_.dispose();
            unmatchedBuilder_ = null;
            unmatched_ = other.unmatched_;
            bitField0_ = (bitField0_ & ~0x00000001);
            unmatchedBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getUnmatchedFieldBuilder() : null;
          } else {
            unmatchedBuilder_.addAllMessages(other.unmatched_);
          }
        }
      }
      if (other.getTotal() != 0) {
        setTotal(other.getTotal());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.stream.v1.UnmatchedLink m =
                  input.readMessage(
                      com.stream.v1.UnmatchedLink.parser(),
                      extensionRegistry);
              if (unmatchedBuilder_ == null) {
                ensureUnmatchedIsMutable();
                unmatched_.add(m);
              } else {
                unmatchedBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 16: {
              total_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.stream.v1.UnmatchedLink> unmatched_ =
      java.util.Collections.emptyList();
    private void ensureUnmatchedIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        unmatched_ = new java.util.ArrayList<com.stream.v1.UnmatchedLink>(unmatched_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.stream.v1.UnmatchedLink, com.stream.v1.UnmatchedLink.Builder, com.stream.v1.UnmatchedLinkOrBuilder> unmatchedBuilder_;

    /**
     * <code>repeated .stream.v1.UnmatchedLink unmatched = 1 [json_name = "unmatched"];</code>
     */
    public java.util.List<com.stream.v1.UnmatchedLink> getUnmatchedList() {
      if (unmatchedBuilder_ == null) {
        return java.util.Collections.unmodifiableList(unmatched_);
      } else {
        return unmatchedBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .stream.v1.UnmatchedLink unmatched = 1 [json_name = "unmatched"];</code>
     */
    public int getUnmatchedCount() {
      if (unmatchedBuilder_ == null) {
        return unmatched_.size();
      } else {
        return unmatchedBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .stream.v1.UnmatchedLink unmatched = 1 [json_name = "unmatched"];</code>
     */
    public com.stream.v1.UnmatchedLink getUnmatched(int index) {
      if (unmatchedBuilder_ == null) {
        return unmatched_.get(index);
      } else {
        return unmatchedBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .stream.v1.UnmatchedLink unmatched = 1 [json_name = "unmatched"];</code>
     */
    public Builder setUnmatched(
        int index, com.stream.v1.UnmatchedLink value) {
      if (unmatchedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUnmatchedIsMutable();
        unmatched_.set(index, value);
        onChanged();
      } else {
        unmatchedBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .stream.v1.UnmatchedLink unmatched = 1 [json_name = "unmatched"];</code>
     */
    public Builder setUnmatched(
        int index, com.stream.v1.UnmatchedLink.Builder builderForValue) {
      if (unmatchedBuilder_ == null) {
        ensureUnmatchedIsMutable();
        unmatched_.set(index, builderForValue.build());
        onChanged();
      } else {
        unmatchedBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .stream.v1.UnmatchedLink unmatched = 1 [json_name = "unmatched"];</code>
     */
    public Builder addUnmatched(com.stream.v1.UnmatchedLink value) {
      if (unmatchedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUnmatchedIsMutable();
        unmatched_.add(value);
        onChanged();
      } else {
        unmatchedBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .stream.v1.UnmatchedLink unmatched = 1 [json_name = "unmatched"];</code>
     */
    public Builder addUnmatched(
        int index, com.stream.v1.UnmatchedLink value) {
      if (unmatchedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUnmatchedIsMutable();
        unmatched_.add(index, value);
        onChanged();
      } else {
        unmatchedBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .stream.v1.UnmatchedLink unmatched = 1 [json_name = "unmatched"];</code>
     */
    public Builder addUnmatched(
        com.stream.v1.UnmatchedLink.Builder builderForValue) {
      if (unmatchedBuilder_ == null) {
        ensureUnmatchedIsMutable();
        unmatched_.add(builderForValue.build());
        onChanged();
      } else {
        unmatchedBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .stream.v1.UnmatchedLink unmatched = 1 [json_name = "unmatched"];</code>
     */
    public Builder addUnmatched(
        int index, com.stream.v1.UnmatchedLink.Builder builderForValue) {
      if (unmatchedBuilder_ == null) {
        ensureUnmatchedIsMutable();
        unmatched_.add(index, builderForValue.build());
        onChanged();
      } else {
        unmatchedBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .stream.v1.UnmatchedLink unmatched = 1 [json_name = "unmatched"];</code>
     */
    public Builder addAllUnmatched(
        java.lang.Iterable<? extends com.stream.v1.UnmatchedLink> values) {
      if (unmatchedBuilder_ == null) {
        ensureUnmatchedIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, unmatched_);
        onChanged();
      } else {
        unmatchedBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .stream.v1.UnmatchedLink unmatched = 1 [json_name = "unmatched"];</code>
     */
    public Builder clearUnmatched() {
      if (unmatchedBuilder_ == null) {
        unmatched_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        unmatchedBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .stream.v1.UnmatchedLink unmatched = 1 [json_name = "unmatched"];</code>
     */
    public Builder removeUnmatched(int index) {
      if (unmatchedBuilder_ == null) {
        ensureUnmatchedIsMutable();
        unmatched_.remove(index);
        onChanged();
      } else {
        unmatchedBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .stream.v1.UnmatchedLink unmatched = 1 [json_name = "unmatched"];</code>
     */
    public com.stream.v1.UnmatchedLink.Builder getUnmatchedBuilder(
        int index) {
      return getUnmatchedFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .stream.v1.UnmatchedLink unmatched = 1 [json_name = "unmatched"];</code>
     */
    public com.stream.v1.UnmatchedLinkOrBuilder getUnmatchedOrBuilder(
        int index) {
      if (unmatchedBuilder_ == null) {
        return unmatched_.get(index);  } else {
        return unmatchedBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .stream.v1.UnmatchedLink unmatched = 1 [json_name = "unmatched"];</code>
     */
    public java.util.List<? extends com.stream.v1.UnmatchedLinkOrBuilder> 
         getUnmatchedOrBuilderList() {
      if (unmatchedBuilder_ != null) {
        return unmatchedBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(unmatched_);
      }
    }
    /**
     * <code>repeated .stream.v1.UnmatchedLink unmatched = 1 [json_name = "unmatched"];</code>
     */
    public com.stream.v1.UnmatchedLink.Builder addUnmatchedBuilder() {
      return getUnmatchedFieldBuilder().addBuilder(
          com.stream.v1.UnmatchedLink.getDefaultInstance());
    }
    /**
     * <code>repeated .stream.v1.UnmatchedLink unmatched = 1 [json_name = "unmatched"];</code>
     */
    public com.stream.v1.UnmatchedLink.Builder addUnmatchedBuilder(
        int index) {
      return getUnmatchedFieldBuilder().addBuilder(
          index, com.stream.v1.UnmatchedLink.getDefaultInstance());
    }
    /**
     * <code>repeated .stream.v1.UnmatchedLink unmatched = 1 [json_name = "unmatched"];</code>
     */
    public java.util.List<com.stream.v1.UnmatchedLink.Builder> 
         getUnmatchedBuilderList() {
      return getUnmatchedFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.stream.v1.UnmatchedLink, com.stream.v1.UnmatchedLink.Builder, com.stream.v1.UnmatchedLinkOrBuilder> 
        getUnmatchedFieldBuilder() {
      if (unmatchedBuilder_ == null) {
        unmatchedBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.stream.v1.UnmatchedLink, com.stream.v1.UnmatchedLink.Builder, com.stream.v1.UnmatchedLinkOrBuilder>(
                unmatched_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        unmatched_ = null;
      }
      return unmatchedBuilder_;
    }

    private int total_ ;
    /**
     * <code>int32 total = 2 [json_name = "total"];</code>
     * @return The total.
     */
    @java.lang.Override
    public int getTotal() {
      return total_;
    }
    /**
     * <code>int32 total = 2 [json_name = "total"];</code>
     * @param value The total to set.
     * @return This builder for chaining.
     */
    public Builder setTotal(int value) {

      total_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 total = 2 [json_name = "total"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTotal() {
      bitField0_ = (bitField0_ & ~0x00000002);
      total_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:stream.v1.UnmatchedResponse)
  }

  // @@protoc_insertion_point(class_scope:stream.v1.UnmatchedResponse)
  private static final com.stream.v1.UnmatchedResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.stream.v1.UnmatchedResponse();
  }

  public static com.stream.v1.UnmatchedResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UnmatchedResponse>
      PARSER = new com.google.protobuf.AbstractParser<UnmatchedResponse>() {
    @java.lang.Override
    public UnmatchedResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UnmatchedResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UnmatchedResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.stream.v1.UnmatchedResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

