// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/discovery.proto
// Protobuf Java Version: 4.29.0

package com.stream.v1;

public interface UnmatchedLinkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.v1.UnmatchedLink)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string url = 1 [json_name = "url"];</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 1 [json_name = "url"];</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>string source_url = 2 [json_name = "sourceUrl"];</code>
   * @return The sourceUrl.
   */
  java.lang.String getSourceUrl();
  /**
   * <code>string source_url = 2 [json_name = "sourceUrl"];</code>
   * @return The bytes for sourceUrl.
   */
  com.google.protobuf.ByteString
      getSourceUrlBytes();

  /**
   * <code>string context = 3 [json_name = "context"];</code>
   * @return The context.
   */
  java.lang.String getContext();
  /**
   * <code>string context = 3 [json_name = "context"];</code>
   * @return The bytes for context.
   */
  com.google.protobuf.ByteString
      getContextBytes();
}
