// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/control.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.stream.v1;

@kotlin.jvm.JvmName("-initializevolumeSetPayload")
public inline fun volumeSetPayload(block: com.stream.v1.VolumeSetPayloadKt.Dsl.() -> kotlin.Unit): com.stream.v1.VolumeSetPayload =
  com.stream.v1.VolumeSetPayloadKt.Dsl._create(com.stream.v1.VolumeSetPayload.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `stream.v1.VolumeSetPayload`
 */
public object VolumeSetPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.stream.v1.VolumeSetPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.stream.v1.VolumeSetPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.stream.v1.VolumeSetPayload = _builder.build()

    /**
     * ```
     * 0.0 - 1.0
     * ```
     *
     * `double level = 1 [json_name = "level"];`
     */
    public var level: kotlin.Double
      @JvmName("getLevel")
      get() = _builder.level
      @JvmName("setLevel")
      set(value) {
        _builder.level = value
      }
    /**
     * ```
     * 0.0 - 1.0
     * ```
     *
     * `double level = 1 [json_name = "level"];`
     */
    public fun clearLevel() {
      _builder.clearLevel()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.stream.v1.VolumeSetPayload.copy(block: `com.stream.v1`.VolumeSetPayloadKt.Dsl.() -> kotlin.Unit): com.stream.v1.VolumeSetPayload =
  `com.stream.v1`.VolumeSetPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

