// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream/v1/control.proto
// Protobuf Java Version: 4.29.0

package com.stream.v1;

public interface VolumeSetPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.v1.VolumeSetPayload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 0.0 - 1.0
   * </pre>
   *
   * <code>double level = 1 [json_name = "level"];</code>
   * @return The level.
   */
  double getLevel();
}
