// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: stream/v1/control.proto

package streamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED   MessageType = 0
	MessageType_MESSAGE_TYPE_REGISTER      MessageType = 1
	MessageType_MESSAGE_TYPE_SESSION_LIST  MessageType = 2
	MessageType_MESSAGE_TYPE_PLAY          MessageType = 3
	MessageType_MESSAGE_TYPE_STOP          MessageType = 4
	MessageType_MESSAGE_TYPE_PULL_BACK     MessageType = 5
	MessageType_MESSAGE_TYPE_PULL_BACK_ACK MessageType = 6
	MessageType_MESSAGE_TYPE_STATE_UPDATE  MessageType = 7
	MessageType_MESSAGE_TYPE_VOLUME_SET    MessageType = 8
	MessageType_MESSAGE_TYPE_PING          MessageType = 9
	MessageType_MESSAGE_TYPE_PONG          MessageType = 10
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "MESSAGE_TYPE_UNSPECIFIED",
		1:  "MESSAGE_TYPE_REGISTER",
		2:  "MESSAGE_TYPE_SESSION_LIST",
		3:  "MESSAGE_TYPE_PLAY",
		4:  "MESSAGE_TYPE_STOP",
		5:  "MESSAGE_TYPE_PULL_BACK",
		6:  "MESSAGE_TYPE_PULL_BACK_ACK",
		7:  "MESSAGE_TYPE_STATE_UPDATE",
		8:  "MESSAGE_TYPE_VOLUME_SET",
		9:  "MESSAGE_TYPE_PING",
		10: "MESSAGE_TYPE_PONG",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED":   0,
		"MESSAGE_TYPE_REGISTER":      1,
		"MESSAGE_TYPE_SESSION_LIST":  2,
		"MESSAGE_TYPE_PLAY":          3,
		"MESSAGE_TYPE_STOP":          4,
		"MESSAGE_TYPE_PULL_BACK":     5,
		"MESSAGE_TYPE_PULL_BACK_ACK": 6,
		"MESSAGE_TYPE_STATE_UPDATE":  7,
		"MESSAGE_TYPE_VOLUME_SET":    8,
		"MESSAGE_TYPE_PING":          9,
		"MESSAGE_TYPE_PONG":          10,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_stream_v1_control_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_stream_v1_control_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_stream_v1_control_proto_rawDescGZIP(), []int{0}
}

type DeviceKind int32

const (
	DeviceKind_DEVICE_KIND_UNSPECIFIED DeviceKind = 0
	DeviceKind_DEVICE_KIND_CONTROLLER  DeviceKind = 1
	DeviceKind_DEVICE_KIND_TARGET      DeviceKind = 2
	DeviceKind_DEVICE_KIND_TV          DeviceKind = 3 // reserved for future TV client
)

// Enum value maps for DeviceKind.
var (
	DeviceKind_name = map[int32]string{
		0: "DEVICE_KIND_UNSPECIFIED",
		1: "DEVICE_KIND_CONTROLLER",
		2: "DEVICE_KIND_TARGET",
		3: "DEVICE_KIND_TV",
	}
	DeviceKind_value = map[string]int32{
		"DEVICE_KIND_UNSPECIFIED": 0,
		"DEVICE_KIND_CONTROLLER":  1,
		"DEVICE_KIND_TARGET":      2,
		"DEVICE_KIND_TV":          3,
	}
)

func (x DeviceKind) Enum() *DeviceKind {
	p := new(DeviceKind)
	*p = x
	return p
}

func (x DeviceKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceKind) Descriptor() protoreflect.EnumDescriptor {
	return file_stream_v1_control_proto_enumTypes[1].Descriptor()
}

func (DeviceKind) Type() protoreflect.EnumType {
	return &file_stream_v1_control_proto_enumTypes[1]
}

func (x DeviceKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceKind.Descriptor instead.
func (DeviceKind) EnumDescriptor() ([]byte, []int) {
	return file_stream_v1_control_proto_rawDescGZIP(), []int{1}
}

// Top-level wrapper for every LMC message.
// to: device UUID for unicast, "broadcast" for all, "server" for hub-only.
// auth: unset in zero-auth mode; populated for future token auth.
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=stream.v1.MessageType" json:"type,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Auth          *string                `protobuf:"bytes,4,opt,name=auth,proto3,oneof" json:"auth,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,5,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_stream_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_stream_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *Envelope) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Envelope) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Envelope) GetAuth() string {
	if x != nil && x.Auth != nil {
		return *x.Auth
	}
	return ""
}

func (x *Envelope) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

// Canonical representation of a connected device.
// Broadcast to all clients on any session change.
type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind          DeviceKind             `protobuf:"varint,3,opt,name=kind,proto3,enum=stream.v1.DeviceKind" json:"kind,omitempty"`
	ChannelId     string                 `protobuf:"bytes,4,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ChannelName   string                 `protobuf:"bytes,5,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	StreamUrl     string                 `protobuf:"bytes,6,opt,name=stream_url,json=streamUrl,proto3" json:"stream_url,omitempty"`
	Playing       bool                   `protobuf:"varint,7,opt,name=playing,proto3" json:"playing,omitempty"`
	Volume        float64                `protobuf:"fixed64,8,opt,name=volume,proto3" json:"volume,omitempty"`
	ConnectedAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_stream_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_stream_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *SessionInfo) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SessionInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SessionInfo) GetKind() DeviceKind {
	if x != nil {
		return x.Kind
	}
	return DeviceKind_DEVICE_KIND_UNSPECIFIED
}

func (x *SessionInfo) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *SessionInfo) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *SessionInfo) GetStreamUrl() string {
	if x != nil {
		return x.StreamUrl
	}
	return ""
}

func (x *SessionInfo) GetPlaying() bool {
	if x != nil {
		return x.Playing
	}
	return false
}

func (x *SessionInfo) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *SessionInfo) GetConnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConnectedAt
	}
	return nil
}

// Sent by a device immediately after connecting.
type RegisterPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind          DeviceKind             `protobuf:"varint,2,opt,name=kind,proto3,enum=stream.v1.DeviceKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPayload) Reset() {
	*x = RegisterPayload{}
	mi := &file_stream_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPayload) ProtoMessage() {}

func (x *RegisterPayload) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPayload.ProtoReflect.Descriptor instead.
func (*RegisterPayload) Descriptor() ([]byte, []int) {
	return file_stream_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterPayload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterPayload) GetKind() DeviceKind {
	if x != nil {
		return x.Kind
	}
	return DeviceKind_DEVICE_KIND_UNSPECIFIED
}

// Instructs a target to begin playback.
type PlayPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ChannelName   string                 `protobuf:"bytes,2,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	StreamUrl     string                 `protobuf:"bytes,3,opt,name=stream_url,json=streamUrl,proto3" json:"stream_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayPayload) Reset() {
	*x = PlayPayload{}
	mi := &file_stream_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayPayload) ProtoMessage() {}

func (x *PlayPayload) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayPayload.ProtoReflect.Descriptor instead.
func (*PlayPayload) Descriptor() ([]byte, []int) {
	return file_stream_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *PlayPayload) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *PlayPayload) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *PlayPayload) GetStreamUrl() string {
	if x != nil {
		return x.StreamUrl
	}
	return ""
}

// Sent by a controller to request the target's stream.
type PullBackPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromDevice    string                 `protobuf:"bytes,1,opt,name=from_device,json=fromDevice,proto3" json:"from_device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullBackPayload) Reset() {
	*x = PullBackPayload{}
	mi := &file_stream_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullBackPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullBackPayload) ProtoMessage() {}

func (x *PullBackPayload) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullBackPayload.ProtoReflect.Descriptor instead.
func (*PullBackPayload) Descriptor() ([]byte, []int) {
	return file_stream_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *PullBackPayload) GetFromDevice() string {
	if x != nil {
		return x.FromDevice
	}
	return ""
}

// Sent by the server to the requesting controller.
type PullBackAckPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ChannelName   string                 `protobuf:"bytes,2,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	StreamUrl     string                 `protobuf:"bytes,3,opt,name=stream_url,json=streamUrl,proto3" json:"stream_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullBackAckPayload) Reset() {
	*x = PullBackAckPayload{}
	mi := &file_stream_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullBackAckPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullBackAckPayload) ProtoMessage() {}

func (x *PullBackAckPayload) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullBackAckPayload.ProtoReflect.Descriptor instead.
func (*PullBackAckPayload) Descriptor() ([]byte, []int) {
	return file_stream_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *PullBackAckPayload) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *PullBackAckPayload) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *PullBackAckPayload) GetStreamUrl() string {
	if x != nil {
		return x.StreamUrl
	}
	return ""
}

// Broadcast by a target on every playback state change.
type StateUpdatePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ChannelName   string                 `protobuf:"bytes,2,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	StreamUrl     string                 `protobuf:"bytes,3,opt,name=stream_url,json=streamUrl,proto3" json:"stream_url,omitempty"`
	Playing       bool                   `protobuf:"varint,4,opt,name=playing,proto3" json:"playing,omitempty"`
	Volume        float64                `protobuf:"fixed64,5,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateUpdatePayload) Reset() {
	*x = StateUpdatePayload{}
	mi := &file_stream_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateUpdatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateUpdatePayload) ProtoMessage() {}

func (x *StateUpdatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateUpdatePayload.ProtoReflect.Descriptor instead.
func (*StateUpdatePayload) Descriptor() ([]byte, []int) {
	return file_stream_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *StateUpdatePayload) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *StateUpdatePayload) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *StateUpdatePayload) GetStreamUrl() string {
	if x != nil {
		return x.StreamUrl
	}
	return ""
}

func (x *StateUpdatePayload) GetPlaying() bool {
	if x != nil {
		return x.Playing
	}
	return false
}

func (x *StateUpdatePayload) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

type VolumeSetPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         float64                `protobuf:"fixed64,1,opt,name=level,proto3" json:"level,omitempty"` // 0.0 - 1.0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeSetPayload) Reset() {
	*x = VolumeSetPayload{}
	mi := &file_stream_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeSetPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeSetPayload) ProtoMessage() {}

func (x *VolumeSetPayload) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeSetPayload.ProtoReflect.Descriptor instead.
func (*VolumeSetPayload) Descriptor() ([]byte, []int) {
	return file_stream_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *VolumeSetPayload) GetLevel() float64 {
	if x != nil {
		return x.Level
	}
	return 0
}

// Wraps the current session list for broadcast.
type SessionListPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionInfo         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionListPayload) Reset() {
	*x = SessionListPayload{}
	mi := &file_stream_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionListPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionListPayload) ProtoMessage() {}

func (x *SessionListPayload) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionListPayload.ProtoReflect.Descriptor instead.
func (*SessionListPayload) Descriptor() ([]byte, []int) {
	return file_stream_v1_control_proto_rawDescGZIP(), []int{8}
}

func (x *SessionListPayload) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

var File_stream_v1_control_proto protoreflect.FileDescriptor

const file_stream_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x17stream/v1/control.proto\x12\tstream.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9f\x01\n" +
	"\bEnvelope\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.stream.v1.MessageTypeR\x04type\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x17\n" +
	"\x04auth\x18\x04 \x01(\tH\x00R\x04auth\x88\x01\x01\x12!\n" +
	"\fpayload_json\x18\x05 \x01(\tR\vpayloadJsonB\a\n" +
	"\x05_auth\"\xbb\x02\n" +
	"\vSessionInfo\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12)\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x15.stream.v1.DeviceKindR\x04kind\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x04 \x01(\tR\tchannelId\x12!\n" +
	"\fchannel_name\x18\x05 \x01(\tR\vchannelName\x12\x1d\n" +
	"\n" +
	"stream_url\x18\x06 \x01(\tR\tstreamUrl\x12\x18\n" +
	"\aplaying\x18\a \x01(\bR\aplaying\x12\x16\n" +
	"\x06volume\x18\b \x01(\x01R\x06volume\x12=\n" +
	"\fconnected_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vconnectedAt\"P\n" +
	"\x0fRegisterPayload\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x15.stream.v1.DeviceKindR\x04kind\"n\n" +
	"\vPlayPayload\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12!\n" +
	"\fchannel_name\x18\x02 \x01(\tR\vchannelName\x12\x1d\n" +
	"\n" +
	"stream_url\x18\x03 \x01(\tR\tstreamUrl\"2\n" +
	"\x0fPullBackPayload\x12\x1f\n" +
	"\vfrom_device\x18\x01 \x01(\tR\n" +
	"fromDevice\"u\n" +
	"\x12PullBackAckPayload\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12!\n" +
	"\fchannel_name\x18\x02 \x01(\tR\vchannelName\x12\x1d\n" +
	"\n" +
	"stream_url\x18\x03 \x01(\tR\tstreamUrl\"\xa7\x01\n" +
	"\x12StateUpdatePayload\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12!\n" +
	"\fchannel_name\x18\x02 \x01(\tR\vchannelName\x12\x1d\n" +
	"\n" +
	"stream_url\x18\x03 \x01(\tR\tstreamUrl\x12\x18\n" +
	"\aplaying\x18\x04 \x01(\bR\aplaying\x12\x16\n" +
	"\x06volume\x18\x05 \x01(\x01R\x06volume\"(\n" +
	"\x10VolumeSetPayload\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x01R\x05level\"H\n" +
	"\x12SessionListPayload\x122\n" +
	"\bsessions\x18\x01 \x03(\v2\x16.stream.v1.SessionInfoR\bsessions*\xb9\x02\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15MESSAGE_TYPE_REGISTER\x10\x01\x12\x1d\n" +
	"\x19MESSAGE_TYPE_SESSION_LIST\x10\x02\x12\x15\n" +
	"\x11MESSAGE_TYPE_PLAY\x10\x03\x12\x15\n" +
	"\x11MESSAGE_TYPE_STOP\x10\x04\x12\x1a\n" +
	"\x16MESSAGE_TYPE_PULL_BACK\x10\x05\x12\x1e\n" +
	"\x1aMESSAGE_TYPE_PULL_BACK_ACK\x10\x06\x12\x1d\n" +
	"\x19MESSAGE_TYPE_STATE_UPDATE\x10\a\x12\x1b\n" +
	"\x17MESSAGE_TYPE_VOLUME_SET\x10\b\x12\x15\n" +
	"\x11MESSAGE_TYPE_PING\x10\t\x12\x15\n" +
	"\x11MESSAGE_TYPE_PONG\x10\n" +
	"*q\n" +
	"\n" +
	"DeviceKind\x12\x1b\n" +
	"\x17DEVICE_KIND_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16DEVICE_KIND_CONTROLLER\x10\x01\x12\x16\n" +
	"\x12DEVICE_KIND_TARGET\x10\x02\x12\x12\n" +
	"\x0eDEVICE_KIND_TV\x10\x03B\xa9\x01\n" +
	"\rcom.stream.v1B\fControlProtoP\x01ZEgithub.com/fredrick-karuri/nativestream/sdk-gen/go/stream/v1;streamv1\xa2\x02\x03SXX\xaa\x02\tStream.V1\xca\x02\tStream\\V1\xe2\x02\x15Stream\\V1\\GPBMetadata\xea\x02\n" +
	"Stream::V1b\x06proto3"

var (
	file_stream_v1_control_proto_rawDescOnce sync.Once
	file_stream_v1_control_proto_rawDescData []byte
)

func file_stream_v1_control_proto_rawDescGZIP() []byte {
	file_stream_v1_control_proto_rawDescOnce.Do(func() {
		file_stream_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stream_v1_control_proto_rawDesc), len(file_stream_v1_control_proto_rawDesc)))
	})
	return file_stream_v1_control_proto_rawDescData
}

var file_stream_v1_control_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_stream_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_stream_v1_control_proto_goTypes = []any{
	(MessageType)(0),              // 0: stream.v1.MessageType
	(DeviceKind)(0),               // 1: stream.v1.DeviceKind
	(*Envelope)(nil),              // 2: stream.v1.Envelope
	(*SessionInfo)(nil),           // 3: stream.v1.SessionInfo
	(*RegisterPayload)(nil),       // 4: stream.v1.RegisterPayload
	(*PlayPayload)(nil),           // 5: stream.v1.PlayPayload
	(*PullBackPayload)(nil),       // 6: stream.v1.PullBackPayload
	(*PullBackAckPayload)(nil),    // 7: stream.v1.PullBackAckPayload
	(*StateUpdatePayload)(nil),    // 8: stream.v1.StateUpdatePayload
	(*VolumeSetPayload)(nil),      // 9: stream.v1.VolumeSetPayload
	(*SessionListPayload)(nil),    // 10: stream.v1.SessionListPayload
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_stream_v1_control_proto_depIdxs = []int32{
	0,  // 0: stream.v1.Envelope.type:type_name -> stream.v1.MessageType
	1,  // 1: stream.v1.SessionInfo.kind:type_name -> stream.v1.DeviceKind
	11, // 2: stream.v1.SessionInfo.connected_at:type_name -> google.protobuf.Timestamp
	1,  // 3: stream.v1.RegisterPayload.kind:type_name -> stream.v1.DeviceKind
	3,  // 4: stream.v1.SessionListPayload.sessions:type_name -> stream.v1.SessionInfo
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_stream_v1_control_proto_init() }
func file_stream_v1_control_proto_init() {
	if File_stream_v1_control_proto != nil {
		return
	}
	file_stream_v1_control_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stream_v1_control_proto_rawDesc), len(file_stream_v1_control_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stream_v1_control_proto_goTypes,
		DependencyIndexes: file_stream_v1_control_proto_depIdxs,
		EnumInfos:         file_stream_v1_control_proto_enumTypes,
		MessageInfos:      file_stream_v1_control_proto_msgTypes,
	}.Build()
	File_stream_v1_control_proto = out.File
	file_stream_v1_control_proto_goTypes = nil
	file_stream_v1_control_proto_depIdxs = nil
}
