// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: stream/v1/pairing.proto

package streamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PairStartRequest is the optional body for POST /api/pair/start. Platform
// is free-text context (e.g. "macOS", "Android") shown to the operator
// approving the request later — not validated or constrained to an enum,
// since new client platforms shouldn't require a proto change to pair.
type PairStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairStartRequest) Reset() {
	*x = PairStartRequest{}
	mi := &file_stream_v1_pairing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairStartRequest) ProtoMessage() {}

func (x *PairStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_pairing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairStartRequest.ProtoReflect.Descriptor instead.
func (*PairStartRequest) Descriptor() ([]byte, []int) {
	return file_stream_v1_pairing_proto_rawDescGZIP(), []int{0}
}

func (x *PairStartRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type PairStartResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Code             string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	ExpiresInSeconds int32                  `protobuf:"varint,3,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PairStartResponse) Reset() {
	*x = PairStartResponse{}
	mi := &file_stream_v1_pairing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairStartResponse) ProtoMessage() {}

func (x *PairStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_pairing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairStartResponse.ProtoReflect.Descriptor instead.
func (*PairStartResponse) Descriptor() ([]byte, []int) {
	return file_stream_v1_pairing_proto_rawDescGZIP(), []int{1}
}

func (x *PairStartResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PairStartResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PairStartResponse) GetExpiresInSeconds() int32 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

// PairStatusResponse is returned to a device polling its own session.
// token and label are populated only once status is "approved".
type PairStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Token         *string                `protobuf:"bytes,2,opt,name=token,proto3,oneof" json:"token,omitempty"`
	Label         *string                `protobuf:"bytes,3,opt,name=label,proto3,oneof" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairStatusResponse) Reset() {
	*x = PairStatusResponse{}
	mi := &file_stream_v1_pairing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairStatusResponse) ProtoMessage() {}

func (x *PairStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_pairing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairStatusResponse.ProtoReflect.Descriptor instead.
func (*PairStatusResponse) Descriptor() ([]byte, []int) {
	return file_stream_v1_pairing_proto_rawDescGZIP(), []int{2}
}

func (x *PairStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PairStatusResponse) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *PairStatusResponse) GetLabel() string {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return ""
}

type PairingSessionSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	RequestedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	Platform      *string                `protobuf:"bytes,4,opt,name=platform,proto3,oneof" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairingSessionSummary) Reset() {
	*x = PairingSessionSummary{}
	mi := &file_stream_v1_pairing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairingSessionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairingSessionSummary) ProtoMessage() {}

func (x *PairingSessionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_pairing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairingSessionSummary.ProtoReflect.Descriptor instead.
func (*PairingSessionSummary) Descriptor() ([]byte, []int) {
	return file_stream_v1_pairing_proto_rawDescGZIP(), []int{3}
}

func (x *PairingSessionSummary) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PairingSessionSummary) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PairingSessionSummary) GetRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestedAt
	}
	return nil
}

func (x *PairingSessionSummary) GetPlatform() string {
	if x != nil && x.Platform != nil {
		return *x.Platform
	}
	return ""
}

type PairPendingResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Sessions      []*PairingSessionSummary `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairPendingResponse) Reset() {
	*x = PairPendingResponse{}
	mi := &file_stream_v1_pairing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairPendingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairPendingResponse) ProtoMessage() {}

func (x *PairPendingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_pairing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairPendingResponse.ProtoReflect.Descriptor instead.
func (*PairPendingResponse) Descriptor() ([]byte, []int) {
	return file_stream_v1_pairing_proto_rawDescGZIP(), []int{4}
}

func (x *PairPendingResponse) GetSessions() []*PairingSessionSummary {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type PairApproveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairApproveRequest) Reset() {
	*x = PairApproveRequest{}
	mi := &file_stream_v1_pairing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairApproveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairApproveRequest) ProtoMessage() {}

func (x *PairApproveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_pairing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairApproveRequest.ProtoReflect.Descriptor instead.
func (*PairApproveRequest) Descriptor() ([]byte, []int) {
	return file_stream_v1_pairing_proto_rawDescGZIP(), []int{5}
}

func (x *PairApproveRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type PairApproveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairApproveResponse) Reset() {
	*x = PairApproveResponse{}
	mi := &file_stream_v1_pairing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairApproveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairApproveResponse) ProtoMessage() {}

func (x *PairApproveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_pairing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairApproveResponse.ProtoReflect.Descriptor instead.
func (*PairApproveResponse) Descriptor() ([]byte, []int) {
	return file_stream_v1_pairing_proto_rawDescGZIP(), []int{6}
}

func (x *PairApproveResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PairApproveResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PairDenyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairDenyResponse) Reset() {
	*x = PairDenyResponse{}
	mi := &file_stream_v1_pairing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairDenyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairDenyResponse) ProtoMessage() {}

func (x *PairDenyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_pairing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairDenyResponse.ProtoReflect.Descriptor instead.
func (*PairDenyResponse) Descriptor() ([]byte, []int) {
	return file_stream_v1_pairing_proto_rawDescGZIP(), []int{7}
}

func (x *PairDenyResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PairDenyResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CredentialSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	RevokedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=revoked_at,json=revokedAt,proto3,oneof" json:"revoked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialSummary) Reset() {
	*x = CredentialSummary{}
	mi := &file_stream_v1_pairing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialSummary) ProtoMessage() {}

func (x *CredentialSummary) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_pairing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialSummary.ProtoReflect.Descriptor instead.
func (*CredentialSummary) Descriptor() ([]byte, []int) {
	return file_stream_v1_pairing_proto_rawDescGZIP(), []int{8}
}

func (x *CredentialSummary) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CredentialSummary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CredentialSummary) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

type CredentialListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   []*CredentialSummary   `protobuf:"bytes,1,rep,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialListResponse) Reset() {
	*x = CredentialListResponse{}
	mi := &file_stream_v1_pairing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialListResponse) ProtoMessage() {}

func (x *CredentialListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_pairing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialListResponse.ProtoReflect.Descriptor instead.
func (*CredentialListResponse) Descriptor() ([]byte, []int) {
	return file_stream_v1_pairing_proto_rawDescGZIP(), []int{9}
}

func (x *CredentialListResponse) GetCredentials() []*CredentialSummary {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type RevokeCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeCredentialRequest) Reset() {
	*x = RevokeCredentialRequest{}
	mi := &file_stream_v1_pairing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeCredentialRequest) ProtoMessage() {}

func (x *RevokeCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_pairing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeCredentialRequest.ProtoReflect.Descriptor instead.
func (*RevokeCredentialRequest) Descriptor() ([]byte, []int) {
	return file_stream_v1_pairing_proto_rawDescGZIP(), []int{10}
}

func (x *RevokeCredentialRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

var File_stream_v1_pairing_proto protoreflect.FileDescriptor

const file_stream_v1_pairing_proto_rawDesc = "" +
	"\n" +
	"\x17stream/v1/pairing.proto\x12\tstream.v1\x1a\x1fgoogle/protobuf/timestamp.proto\".\n" +
	"\x10PairStartRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\"t\n" +
	"\x11PairStartResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12,\n" +
	"\x12expires_in_seconds\x18\x03 \x01(\x05R\x10expiresInSeconds\"v\n" +
	"\x12PairStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x19\n" +
	"\x05token\x18\x02 \x01(\tH\x00R\x05token\x88\x01\x01\x12\x19\n" +
	"\x05label\x18\x03 \x01(\tH\x01R\x05label\x88\x01\x01B\b\n" +
	"\x06_tokenB\b\n" +
	"\x06_label\"\xb7\x01\n" +
	"\x15PairingSessionSummary\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12=\n" +
	"\frequested_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vrequestedAt\x12\x1f\n" +
	"\bplatform\x18\x04 \x01(\tH\x00R\bplatform\x88\x01\x01B\v\n" +
	"\t_platform\"S\n" +
	"\x13PairPendingResponse\x12<\n" +
	"\bsessions\x18\x01 \x03(\v2 .stream.v1.PairingSessionSummaryR\bsessions\"*\n" +
	"\x12PairApproveRequest\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\"L\n" +
	"\x13PairApproveResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"I\n" +
	"\x10PairDenyResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xb3\x01\n" +
	"\x11CredentialSummary\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12>\n" +
	"\n" +
	"revoked_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\trevokedAt\x88\x01\x01B\r\n" +
	"\v_revoked_at\"X\n" +
	"\x16CredentialListResponse\x12>\n" +
	"\vcredentials\x18\x01 \x03(\v2\x1c.stream.v1.CredentialSummaryR\vcredentials\"/\n" +
	"\x17RevokeCredentialRequest\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05labelB\xa9\x01\n" +
	"\rcom.stream.v1B\fPairingProtoP\x01ZEgithub.com/fredrick-karuri/nativestream/sdk-gen/go/stream/v1;streamv1\xa2\x02\x03SXX\xaa\x02\tStream.V1\xca\x02\tStream\\V1\xe2\x02\x15Stream\\V1\\GPBMetadata\xea\x02\n" +
	"Stream::V1b\x06proto3"

var (
	file_stream_v1_pairing_proto_rawDescOnce sync.Once
	file_stream_v1_pairing_proto_rawDescData []byte
)

func file_stream_v1_pairing_proto_rawDescGZIP() []byte {
	file_stream_v1_pairing_proto_rawDescOnce.Do(func() {
		file_stream_v1_pairing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stream_v1_pairing_proto_rawDesc), len(file_stream_v1_pairing_proto_rawDesc)))
	})
	return file_stream_v1_pairing_proto_rawDescData
}

var file_stream_v1_pairing_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_stream_v1_pairing_proto_goTypes = []any{
	(*PairStartRequest)(nil),        // 0: stream.v1.PairStartRequest
	(*PairStartResponse)(nil),       // 1: stream.v1.PairStartResponse
	(*PairStatusResponse)(nil),      // 2: stream.v1.PairStatusResponse
	(*PairingSessionSummary)(nil),   // 3: stream.v1.PairingSessionSummary
	(*PairPendingResponse)(nil),     // 4: stream.v1.PairPendingResponse
	(*PairApproveRequest)(nil),      // 5: stream.v1.PairApproveRequest
	(*PairApproveResponse)(nil),     // 6: stream.v1.PairApproveResponse
	(*PairDenyResponse)(nil),        // 7: stream.v1.PairDenyResponse
	(*CredentialSummary)(nil),       // 8: stream.v1.CredentialSummary
	(*CredentialListResponse)(nil),  // 9: stream.v1.CredentialListResponse
	(*RevokeCredentialRequest)(nil), // 10: stream.v1.RevokeCredentialRequest
	(*timestamppb.Timestamp)(nil),   // 11: google.protobuf.Timestamp
}
var file_stream_v1_pairing_proto_depIdxs = []int32{
	11, // 0: stream.v1.PairingSessionSummary.requested_at:type_name -> google.protobuf.Timestamp
	3,  // 1: stream.v1.PairPendingResponse.sessions:type_name -> stream.v1.PairingSessionSummary
	11, // 2: stream.v1.CredentialSummary.created_at:type_name -> google.protobuf.Timestamp
	11, // 3: stream.v1.CredentialSummary.revoked_at:type_name -> google.protobuf.Timestamp
	8,  // 4: stream.v1.CredentialListResponse.credentials:type_name -> stream.v1.CredentialSummary
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_stream_v1_pairing_proto_init() }
func file_stream_v1_pairing_proto_init() {
	if File_stream_v1_pairing_proto != nil {
		return
	}
	file_stream_v1_pairing_proto_msgTypes[2].OneofWrappers = []any{}
	file_stream_v1_pairing_proto_msgTypes[3].OneofWrappers = []any{}
	file_stream_v1_pairing_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stream_v1_pairing_proto_rawDesc), len(file_stream_v1_pairing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stream_v1_pairing_proto_goTypes,
		DependencyIndexes: file_stream_v1_pairing_proto_depIdxs,
		MessageInfos:      file_stream_v1_pairing_proto_msgTypes,
	}.Build()
	File_stream_v1_pairing_proto = out.File
	file_stream_v1_pairing_proto_goTypes = nil
	file_stream_v1_pairing_proto_depIdxs = nil
}
